// ui/src/app/cohort-search/modifier-page/modifier-page.component.ts
import {select} from '@angular-redux/store';
import {
  AfterContentChecked,
  ChangeDetectorRef,
  Component,
  EventEmitter,
  OnDestroy,
  OnInit,
  Output
} from '@angular/core';
import {FormArray, FormControl, FormGroup, Validators} from '@angular/forms';
import {
  activeCriteriaType,
  activeModifierList,
  CohortSearchActions,
  previewStatus,
} from 'app/cohort-search/redux';
import {dateValidator, integerAndRangeValidator} from 'app/cohort-search/validators';
import {currentWorkspaceStore} from 'app/utils/navigation';
import {CohortBuilderService, ModifierType, Operator, TreeType} from 'generated';
import {fromJS, List, Map} from 'immutable';
import * as moment from 'moment';
import {Observable} from 'rxjs/Observable';
import {Subscription} from 'rxjs/Subscription';

@Component({
  selector: 'crit-modifier-page',
  templateUrl: './modifier-page.component.html',
  styleUrls: ['./modifier-page.component.css']
})
export class ModifierPageComponent implements OnInit, OnDestroy, AfterContentChecked {
  @select(activeCriteriaType) ctype$;
  @select(activeModifierList) modifiers$;
  @select(previewStatus) preview$;
  @Output() disabled = new EventEmitter<boolean>();
  formChanges = false;
  ctype: string;
  existing = List();
  preview = Map();
  dateObjs = [null , null];
  subscription: Subscription;
  dropdownOption = {
    selected: ['Any', 'Any', 'Any', 'Any']
  };
  visitCounts: any;

  readonly modifiers = [{
    name: 'ageAtEvent',
    label: 'Age At Event',
    inputType: 'number',
    min: 1,
    max: 120,
    maxLength: 3,
    modType: ModifierType.AGEATEVENT,
    operators: [{
      name: 'Any',
      value: undefined,
    }, {
      name: 'Greater Than or Equal To',
      value: 'GREATER_THAN_OR_EQUAL_TO',
    }, {
      name: 'Less Than or Equal To',
      value: 'LESS_THAN_OR_EQUAL_TO',
    }, {
      name: 'Between',
      value: 'BETWEEN',
    }],
  }, {
    name: 'eventDate',
    label: 'Shifted Event Date',
    inputType: 'date',
    min: null,
    max: null,
    maxLength: null,
    modType: ModifierType.EVENTDATE,
    operators: [{
      name: 'Any',
      value: undefined,
    }, {
      name: 'Is On or Before',
      value: 'LESS_THAN_OR_EQUAL_TO',
    }, {
      name: 'Is On or After',
      value: 'GREATER_THAN_OR_EQUAL_TO',
    }, {
      name: 'Is Between',
      value: 'BETWEEN',
    }]
  }, {
    name: 'hasOccurrences',
    label: 'Has Occurrences',
    inputType: 'number',
    min: 1,
    max: 99,
    maxLength: 2,
    modType: ModifierType.NUMOFOCCURRENCES,
    operators: [{
      name: 'Any',
      value: undefined,
    }, {
      name: 'N or More',
      value: 'GREATER_THAN_OR_EQUAL_TO',
    }]
  }];

  form = new FormGroup({
    ageAtEvent: new FormGroup({
      operator: new FormControl(),
      valueA: new FormControl(),
      valueB: new FormControl(),
    }),
    hasOccurrences: new FormGroup({
      operator: new FormControl(),
      valueA: new FormControl(),
      valueB: new FormControl(),
    }),
    eventDate: new FormGroup({
      operator: new FormControl(),
      valueA: new FormControl(),
      valueB: new FormControl(),
    }),
  });

  dateA = new FormControl();
  dateB = new FormControl();
  errors = new Set();
  constructor(
    private actions: CohortSearchActions,
    private api: CohortBuilderService,
    private cdref: ChangeDetectorRef,
  ) {}

  ngOnInit() {
    const cdrid = +(currentWorkspaceStore.getValue().cdrVersionId);
    this.subscription = this.modifiers$.subscribe(mods => this.existing = mods);
    this.subscription.add(this.ctype$
      .filter(ctype => !! ctype)
      .subscribe(ctype => {
        this.ctype = ctype;
        if (this.addEncounters) {
          this.modifiers.push({
            name: 'encounters',
            label: 'During Visit Type',
            inputType: null,
            min: null,
            max: null,
            maxLength: null,
            modType: ModifierType.ENCOUNTERS,
            operators: [{
              name: 'Any',
              value: undefined,
            }]
          });
          this.form.addControl('encounters',
            new FormGroup({operator: new FormControl(),
              encounterType: new FormControl()}));
          this.api.getCriteriaBy(cdrid, TreeType[TreeType.VISIT], null, true, 0)
            .filter(response => !!response)
            .subscribe(response => {
              this.visitCounts = {};
              response.items.forEach(option => {
                if (option.parentId === 0 && option.count > 0) {
                  this.modifiers[3].operators.push({
                    name: option.name,
                    value: option.conceptId.toString()
                  });
                  this.visitCounts[option.conceptId] = option.count;
                }
              });
            });
        }
      })
    );

    this.subscription.add(this.preview$.subscribe(prev => this.preview = prev));

    // This reseeds the form with existing data if we're editing an existing group
    this.subscription.add(this.modifiers$.first().subscribe(mods => {
      mods.forEach(mod => {
        const meta = this.modifiers.find(_mod => mod.get('name') === _mod.modType);
        if (meta) {
          if (meta.modType === ModifierType.ENCOUNTERS) {
            let selected;
            // make sure the encounters options are loaded before setting the value
            Observable.interval(100)
              .takeWhile((val, index) => !selected && index < 30)
              .subscribe(i => {
                selected = meta.operators.find(
                  operator => operator.value
                    && operator.value.toString() === mod.getIn(['operands', 0])
                );
                if (selected) {
                  this.dropdownOption.selected[3] = selected.name;
                  this.form.get(meta.name).patchValue({
                    operator: mod.getIn(['operands', 0]),
                    encounterType: mod.get('encounterType')
                  }, {emitEvent: false});
                }
              });
          } else {
            const selected = meta.operators.find(
              operator => operator.value === mod.get('operator')
            );
            const index = this.modifiers.indexOf(meta);
            this.dropdownOption.selected[index] = selected.name;
            this.ngAfterContentChecked();
            if (meta.modType === ModifierType.EVENTDATE) {
              this.dateObjs = [
                new Date(mod.getIn(['operands', 0]) + 'T08:00:00'),
                new Date(mod.getIn(['operands', 1]) + 'T08:00:00')
              ];
            }
            this.form.get(meta.name).patchValue({
              operator: mod.get('operator'),
              valueA: mod.getIn(['operands', 0]),
              valueB: mod.getIn(['operands', 1]),
            }, {emitEvent: false});
          }
        }
      });
    }));

    this.subscription.add(this.form.valueChanges
      .do(console.log)
      .map(vals => this.currentMods(vals))
      .subscribe(newMods => {
        /*
         * NOTE: the way this process works is basically as follows: 1) compute
         * a modifier per modifier category 2) merge those with the existing
         * modifiers 3) check for any existing modifiers that no longer exist
         * and remove them 4) iterate through the new mods and add them
         *
         * This is a "good enough for now" kind of thing.  If it gets too slow,
         * then the faster way would be to have an "update mods" action" and
         * move all the work into the reducer, effectively ending the story at
         * step two.  Leaving it this way, though, gives us some flexibility
         * with individual modifiers if we need it.
         */
        this.existing
          .filter(mod => !newMods.includes(mod))
          .forEach(mod => this.actions.removeModifier(mod));

        // dispatch the new
        newMods
          .filter(mod => !!mod)
          .filter(mod => !this.existing.includes(mod))
          .forEach(mod => this.actions.addModifier(mod));

        // update the calculate button
        this.formChanges = !newMods.every(element => element === undefined);
        // clear preview/counts
        this.preview = Map();
      })
    );

    this.subscription.add(this.dateA.valueChanges.subscribe(value => {
      const formatted = moment(value).format('YYYY-MM-DD');
      this.form.get(['eventDate', 'valueA']).setValue(formatted);
    }));

    this.subscription.add(this.dateB.valueChanges.subscribe(value => {
      const formatted = moment(value).format('YYYY-MM-DD');
      this.form.get(['eventDate', 'valueB']).setValue(formatted);
    }));
  }

  ngAfterContentChecked() {
    this.cdref.detectChanges();
  }

  showCount(modName: string, optName: string) {
    return modName === 'encounters' && optName !== 'Any';
  }

  selectChange(opt, index, e, mod) {
    this.dropdownOption.selected[index] = opt.name;
    const modForm = <FormArray>this.form.controls[mod.name];
    const valueForm = <FormArray>modForm;
    if (mod.name === 'encounters') {
      valueForm.get('encounterType').patchValue(opt.name);
    } else {
      if (opt.name === 'Any') {
        this.form.get([mod.name, 'valueA']).clearValidators();
        this.form.get([mod.name, 'valueB']).clearValidators();
        this.form.get(mod.name).reset();
      } else {
        const validators = [Validators.required];
        if (mod.modType === ModifierType.EVENTDATE) {
          validators.push(dateValidator());
        } else {
          validators.push(integerAndRangeValidator(mod.label, mod.min, mod.max));
          validators.push(Validators.maxLength(mod.maxLength));
        }
        this.form.get([mod.name, 'valueA']).setValidators(validators);
        if (opt.value === Operator.BETWEEN) {
          this.form.get([mod.name, 'valueB']).setValidators(validators);
        } else {
          this.form.get([mod.name, 'valueB']).clearValidators();
          this.form.get([mod.name, 'valueB']).reset();
        }
      }
    }
    valueForm.get('operator').patchValue(opt.value);
  }

  currentMods(vals) {
    this.ngAfterContentChecked();
    this.errors = new Set();
    return this.modifiers.map(mod => {
      const {name, inputType, maxLength, modType} = mod;
      if (modType === ModifierType.ENCOUNTERS) {
        if (!vals[name].operator) {
          return;
        }
        return fromJS({name: modType, operator: 'IN',
          encounterType: vals[name].encounterType.toString(),
          operands: [vals[name].operator.toString()]});
      } else {
        const {operator, valueA, valueB} = vals[name];
        const between = operator === 'BETWEEN';
        if (!operator || (!valueA && !valueB)) {
          if (inputType !== 'date'
            && (this.form.get([name, 'valueA']).dirty || this.form.get([name, 'valueB']).dirty)) {
            this.errors.add({name, type: 'integer'});
          }
          return;
        }
        if (inputType === 'date') {
          const dateValueA = moment(valueA).format('YYYY-MM-DD');
          const dateValueB = moment(valueB).format('YYYY-MM-DD');
          const operands = [dateValueA];
          if (between && dateValueB) {
            operands.push(dateValueB);
          }
          return fromJS({name: modType, operator, operands});
        } else {
          const operands = [valueA];
          if (between) {
            operands.push(valueB);
          }
          operands.forEach((value, i) => {
            const input = i === 0 ? 'valueA' : 'valueB';
            if (value && value.length > maxLength) {
              value = value.slice(0, maxLength);
              this.form.get([name, input]).setValue(value, {emitEvent: false});
            }
          });
          return fromJS({name: modType, operator, operands});
        }
      }
    });
  }

  get addEncounters() {
    return [TreeType[TreeType.PM], TreeType[TreeType.VISIT]].indexOf(TreeType[this.ctype]) === -1
      && !this.modifiers.find(modifier => modifier.modType === ModifierType.ENCOUNTERS);
  }

  requestPreview() {
    this.actions.requestPreview();
  }

  ngOnDestroy() {
    this.subscription.unsubscribe();
  }

  dateBlur(index: number) {
    const control = index === 0 ? 'valueA' : 'valueB';
    this.dateObjs[index] = new Date(this.form.get(['eventDate', control]).value + 'T08:00:00');
  }

  get disableCalculate() {
    const disable = !!this.preview.get('requesting') || !!this.errors.size || this.form.invalid;
    this.disabled.emit(disable);
    return disable;
  }
}

<form [formGroup]="form">
  <section class="form-block">
    <div class="modifier-header">
      The following modifiers are optional and apply to all selected criteria
    </div>
    <div *ngIf="preview.get('error')" class="alert alert-danger alert-sm">
      <div class="alert-items">
        <div class="alert-item static">
          <div class="alert-text">
            A problem occurred and we were not able to retrieve the requested data
          </div>
        </div>
      </div>
    </div>
    <div *ngFor="let mod of modifiers; let i = index" [formGroupName]="mod.name">
      <div class="label-flex">
        <label class="modifier-event-header" [for]="mod.name">{{ mod.label }}</label>
        <ng-container *ngIf = "mod.label === 'Shifted Event Date'">
          <small class="name"
                 [popper]="codesPopper"
                 [popperTrigger]="'hover'"
                 [popperPlacement]="'top'">
            <div class="label-info">
              <clr-icon  class=" is-solid" shape="info-standard"></clr-icon>
            </div>
          </small>
          <popper-content #codesPopper>
            <p class="tooltip-text" [style.margin]="'0'">
              Dates are consistently shifted within a participant’s record
              by a time period of up to 364 days backwards.
              The date shift differs across participants.</p>
          </popper-content>
        </ng-container>
      </div>
        <div class="modifier-container">
          <div class="dropdown-width ">
            <clr-dropdown >
              <button type="button" class="btn btn-outline" clrDropdownTrigger>
                <span>{{dropdownOption.selected[i]}}</span>
                <clr-icon shape="caret down"></clr-icon>
              </button>
              <clr-dropdown-menu [class.encounters]="mod.name === 'encounters'"  clrPosition="bottom-left" *clrIfOpen>
                <button
                  *ngFor="let opt of mod.operators"
                  [value]="opt.value"
                  (click)="selectChange(opt, i, $event, mod)"
                  class="dropdown-item"
                  type="button"
                  clrDropdownItem>
                  {{ opt.name}}
                  <span *ngIf="showCount(mod.name, opt.name)" class="badge badge-info">
                    {{ visitCounts[opt.value] | number }}
                  </span>
                </button>
              </clr-dropdown-menu>
            </clr-dropdown>
          </div>
          <ng-container *ngIf="dropdownOption.selected[i] !== 'Any'">
            <ng-container *ngIf="mod.inputType">
              <div>
                <input *ngIf="mod.inputType !== 'date'" min="0"  (keypress)="numberValidation($event)" class="modifier-event-indicator" formControlName="valueA" [type]="mod.inputType">
              </div>
              <div *ngIf="mod.inputType === 'date'" >
                <input class="modifier-calender" type="text" placeholder="YYYY-MM-DD" (blur)="dateBlur(0)" formControlName="valueA">
                <input class="hidden-input" type="date" [formControl]="dateA" [(clrDate)]="dateObjs[0]">
              </div>
              <ng-container  *ngIf="dropdownOption.selected[i] === 'Between'">
                <div class="and-text">
                  <div>and</div>
                </div>
                <div>
                  <input *ngIf="mod.inputType !== 'date'"  min="0"  (keypress)="numberValidation($event)" class="modifier-event-indicator" formControlName="valueB" [type]="mod.inputType">
                </div>
              </ng-container>
              <ng-container *ngIf="dropdownOption.selected[i] === 'Is Between'">
                <div class="and-text" >
                  <div>and</div>
                </div>
                <div>
                  <input class="modifier-calender" type="text" placeholder="YYYY-MM-DD" (blur)="dateBlur(1)" formControlName="valueB">
                  <input class="hidden-input" type="date" [formControl]="dateB" [(clrDate)]="dateObjs[1]">
                </div>
              </ng-container>
            </ng-container>
          </ng-container>
        </div>
    </div>
  </section>
</form>
<div class="container count-preview">
  <div class="row">
    <div class="col-lg-3">
      <button type="button" [ngClass]="[ preview.get('requesting')? 'greyed-button': 'calculate-btn']"
        class="btn "
        [clrLoading]="preview.get('requesting')"
        (click)="requestPreview()"
        [disabled] = "!formChanges">
        Calculate
      </button>
    </div>
    <ng-container *ngIf="!preview.get('requesting')" >
      <div class="col-lg-8 text-padding" *ngIf="preview.get('count') >= 0">
        <div class="result-text">
          Results
        </div>
        <div>
          Number Participants:
          <span class="text-bold" *ngIf="!preview.get('requesting')">
         {{ preview.get('count', 0) | number }}
        </span>
        </div>
      </div>
    </ng-container>
  </div>
</div>

// ui/src/app/cohort-search/modifier-page/modifier-page.component.tsx
import * as fp from 'lodash/fp';
import * as moment from 'moment';
import {Dropdown} from 'primereact/dropdown';
import * as React from 'react';

import {CalculateFooter} from 'app/cohort-search/attributes-page-v2/attributes-page-v2.component';
import {encountersStore} from 'app/cohort-search/search-state.service';
import {domainToTitle, mapParameter} from 'app/cohort-search/utils';
import {Button} from 'app/components/buttons';
import {FlexRowWrap} from 'app/components/flex';
import {ClrIcon} from 'app/components/icons';
import {DatePicker, NumberInput} from 'app/components/inputs';
import {TooltipTrigger} from 'app/components/popups';
import {cohortBuilderApi} from 'app/services/swagger-fetch-clients';
import colors from 'app/styles/colors';
import {reactStyles, withCurrentCohortSearchContext, withCurrentWorkspace} from 'app/utils';
import {triggerEvent} from 'app/utils/analytics';
import {currentCohortSearchContextStore, serverConfigStore} from 'app/utils/navigation';
import {WorkspaceData} from 'app/utils/workspace-data';
import {Criteria, CriteriaType, DomainType, ModifierType, Operator} from 'generated/fetch';


const styles = reactStyles({
  header: {
    color: '#262262',
    fontWeight: 600,
    fontSize: '16px',
    borderBottom: '1px solid #262262',
    paddingBottom: '0.5rem'
  },
  errors: {
    background: '#f5dbd9',
    color: '#565656',
    fontSize: '11px',
    border: '1px solid #ebafa6',
    borderRadius: '3px',
    marginTop: '0.25rem',
    padding: '3px 5px'
  },
  errorItem: {
    lineHeight: '16px',
  },
  label: {
    color: '#262262',
    fontWeight: 500,
  },
  modifier: {
    marginTop: '0.4rem'
  },
  select: {
    width: '12rem',
    height: '1.6rem',
    paddingLeft: '0.5rem',
    marginRight: '1rem',
  },
  date: {
    width: '6.5rem',
    display: 'inline-block',
  },
  count: {
    display: 'inline-flex',
    height: '0.625rem',
    background: '#0079b8',
    color: '#ffffff',
    fontSize: '10px',
    padding: '0 0.166667rem',
    borderRadius: '10px',
    verticalAlign: 'middle',
    alignItems: 'center',
  },
  info: {
    color: '#0077b7',
    marginLeft: '0.25rem',
  },
  footer: {
    position: 'absolute',
    bottom: '1rem'
  },
  row: {
    display: 'flex',
    flexWrap: 'wrap',
    marginRight: '-.5rem',
    marginLeft: '-.5rem'
  },
  col: {
    position: 'relative',
    minHeight: '1px',
    width: '100%',
    paddingLeft: '0.5rem',
    paddingRight: '0.5rem',
  },
  button: {
    color: '#ffffff',
    height: '1.5rem',
    margin: '0.25rem 0.5rem 0.25rem 0',
    borderRadius: '3px',
  },
  previewCount: {
    color: '#4a4a4a',
    fontWeight: 'bold'
  },
  error: {
    background: '#F7981C',
    color: '#ffffff',
    fontSize: '12px',
    fontWeight: 500,
    textAlign: 'left',
    border: '1px solid #ebafa6',
    borderRadius: '5px',
    marginTop: '0.25rem',
    padding: '8px',
  },
  addButton: {
    height: '2rem',
    borderRadius: '5px',
    fontWeight: 600,
    marginRight: '0.5rem'
  }
});

const validatorFuncs = {
  AGE_AT_EVENT: (value) => {
    if (value === '') {
      return 'Age At Event is required';
    }
    if (value < 0 || value > 120) {
      return 'Age At Event must be between 0 - 120';
    }
    if (!Number.isInteger(parseFloat(value))) {
      return 'Age At Event must be a whole number';
    }
    return null;
  },
  EVENT_DATE: (value) => {
    if (value === '') {
      return 'Event Date is required';
    }
    if (!moment(value, 'YYYY-MM-DD', true).isValid()) {
      return 'Dates must be in format \'YYYY-MM-DD\'';
    }
    return null;
  },
  NUM_OF_OCCURRENCES: (value) => {
    if (value === '') {
      return 'Has Occurrences is required';
    }
    if (value < 1 || value > 99) {
      return 'Has Occurrences must be between 1 - 99';
    }
    if (!Number.isInteger(parseFloat(value))) {
      return 'Has Occurrences must be a whole number';
    }
    return null;
  }
};
const SURVEY_MODIFIERS = [ModifierType.AGEATEVENT];

interface Selection extends Criteria {
  parameterId: string;
}

interface Props {
  selections: Array<Selection>;
  closeModifiers: Function;
  workspace: WorkspaceData;
  cohortContext: any;
}

interface State {
  calculateError: boolean;
  count: number;
  formErrors: Array<string>;
  formState: any;
  formUntouched: boolean;
  initialFormState: boolean;
  visitCounts: any;
  loading: boolean;
}

export const ModifierPage = fp.flow(withCurrentWorkspace(), withCurrentCohortSearchContext())(
  class extends React.Component<Props, State> {
    constructor(props: Props) {
      super(props);
      this.state = {
        formState: [{
          name: ModifierType.AGEATEVENT,
          label: 'Age At Event',
          type: 'number',
          operator: undefined,
          values: [undefined, undefined],
          options: [{
            label: 'Any',
            value: undefined,
          }, {
            label: 'Greater Than or Equal To',
            value: Operator.GREATERTHANOREQUALTO,
          }, {
            label: 'Less Than or Equal To',
            value: Operator.LESSTHANOREQUALTO,
          }, {
            label: 'Between',
            value: Operator.BETWEEN,
          }]
        }, {
          name: ModifierType.NUMOFOCCURRENCES,
          label: 'Has Occurrences',
          type: 'number',
          operator: undefined,
          values: [undefined, undefined],
          options: [{
            label: 'Any',
            value: undefined,
          }, {
            label: 'N or More',
            value: Operator.GREATERTHANOREQUALTO,
          }]
        }],
        formErrors: [],
        formUntouched: false,
        initialFormState: true,
        loading: false,
        count: null,
        visitCounts: undefined,
        calculateError: false,
      };
    }

    async componentDidMount() {
      const {workspace: {cdrVersionId}} = this.props;
      const formState = this.formState;
      if (serverConfigStore.getValue().enableEventDateModifier) {
        formState.push({
          name: ModifierType.EVENTDATE,
          label: 'Event Date',
          type: 'date',
          operator: undefined,
          values: [undefined, undefined],
          options: [{
            label: 'Any',
            value: undefined,
          }, {
            label: 'Is On or Before',
            value: Operator.LESSTHANOREQUALTO,
          }, {
            label: 'Is On or After',
            value: Operator.GREATERTHANOREQUALTO,
          }, {
            label: 'Is Between',
            value: Operator.BETWEEN,
          }]
        });
      }
      if (this.addEncounters) {
        let encountersOptions = encountersStore.getValue();
        if (!encountersOptions) {
          // get options for visit modifier from api
          const res = await cohortBuilderApi().findCriteriaBy(
            +cdrVersionId, DomainType[DomainType.VISIT], CriteriaType[CriteriaType.VISIT]);
          encountersOptions = res.items;
          encountersStore.next(encountersOptions);
        }
        const visitCounts = {};
        const encounters = {
          name: ModifierType.ENCOUNTERS,
          label: 'During Visit Type',
          type: null,
          operator: undefined,
          values: [undefined],
          options: [{
            label: 'Any',
            value: undefined,
          }]
        };
        encountersOptions.forEach(option => {
          if (option.parentId === 0 && option.count > 0) {
            encounters.options.push({
              label: option.name,
              value: option.conceptId.toString()
            });
            visitCounts[option.conceptId] = option.count;
          }
        });
        formState.push(encounters);
        this.setState({visitCounts});
      }
      this.setState({formState});
      this.getExisting();
    }

    get formState() {
      const {cohortContext: {domain}} = this.props;
      const {formState} = this.state;
      return domain === DomainType.SURVEY ?
        formState.filter(form => SURVEY_MODIFIERS.indexOf(form.name) > -1) : formState;
    }

    getExisting() {
      const {cohortContext} = this.props;
      const formState = this.formState;
      // This reseeds the form state with existing data if we're editing an existing item
      cohortContext.item.modifiers.forEach(existing => {
        const index = formState.findIndex(mod => existing.name === mod.name);
        if (index > -1) {
          const mod = formState[index];
          const values = existing.operands.filter(val => !!val);
          switch (mod.name) {
            case ModifierType.ENCOUNTERS:
              formState[index] = {...mod, operator: existing.operands[0], values};
              break;
            case ModifierType.EVENTDATE:
              formState[index] = {
                ...mod,
                operator: existing.operator,
                values: values.map(val => new Date(val + 'T08:00:00'))
              };
              break;
            default:
              formState[index] = {...mod, operator: existing.operator, values};
          }
        }
      });
      this.setState({formState});
    }

    selectChange = (sel: any, index: number) => {
      const {formState} = this.state;
      this.trackEvent(formState[index].label);
      const {name} = formState[index];
      if (name === ModifierType.ENCOUNTERS) {
        formState[index].values = [sel];
      } else if (!sel) {
        formState[index].values = [undefined, undefined];
      } else if (sel !== Operator.BETWEEN) {
        formState[index].values[1] = undefined;
      }
      formState[index].operator = sel;
      this.setState({count: null, formState}, () => this.validateValues());
    }

    inputChange = (index: string, field: string, value: any) => {
      const {formState} = this.state;
      formState[index].values[field] = value;
      this.setState({count: null, formState}, () => this.validateValues());
    }

    updateMods() {
      const {cohortContext} = this.props;
      const {formState} = this.state;
      cohortContext.item.modifiers = formState.reduce((acc, mod) => {
        const {name, operator, values} = mod;
        if (operator) {
          switch (name) {
            case ModifierType.ENCOUNTERS:
              acc.push({name, operator: Operator.IN, operands: [operator.toString()]});
              break;
            case ModifierType.EVENTDATE:
              const formatted = values.map(val => moment(val, 'YYYY-MM-DD', true).isValid()
                    ? moment(val).format('YYYY-MM-DD') : undefined);
              acc.push({name, operator, operands: formatted.filter(val => !!val)});
              break;
            default:
              acc.push({name, operator, operands: values.filter(val => !!val)});
          }
        }
        return acc;
      }, []);
      currentCohortSearchContextStore.next(cohortContext);
      this.props.closeModifiers();
    }

    get addEncounters() {
      const {cohortContext: {domain}} = this.props;
      return ![DomainType.PHYSICALMEASUREMENT, DomainType.VISIT].includes(domain);
    }

    calculate = async() => {
      const {
        selections,
        cohortContext: {domain, item: {modifiers}, role},
        workspace: {cdrVersionId}
      } = this.props;
      this.trackEvent('Calculate');
      try {
        this.setState({loading: true, count: null, calculateError: false});
        const request = {
          includes: [],
          excludes: [],
          [role]: [{
            items: [{
              type: domain,
              searchParameters: selections.map(mapParameter),
              modifiers: modifiers
            }]
          }],
          dataFilters: []
        };
        await cohortBuilderApi().countParticipants(+cdrVersionId, request)
          .then(response => this.setState({count: response, loading: false}));
      } catch (error) {
        console.error(error);
        this.setState({loading: false, calculateError: true});
      }
    }

    trackEvent = (label: string) => {
      const {cohortContext: {domain}} = this.props;
      triggerEvent(
        'Cohort Builder Search',
        'Click',
        `Modifiers - ${label} - ${domainToTitle(domain)} - Cohort Builder Search`
      );
    }

    validateValues() {
      const {formState} = this.state;
      let initialState = true;
      let untouched = false;
      const errors = formState.reduce((acc, item) => {
        if (item.name !== ModifierType.ENCOUNTERS) {
          item.values.forEach((val, v) => {
            if (val !== undefined) {
              initialState = false;
              const error = validatorFuncs[item.name](val);
              if (error) {
                acc.add(error);
              }
            } else if (item.operator !== undefined) {
              initialState = false;
              if (v === 0 || (v === 1 && item.operator === Operator.BETWEEN)) {
                untouched = true;
              }
            }
          });
        } else if (item.values[0] !== undefined) {
          initialState = false;
        }
        return acc;
      }, new Set());
      this.setState({formErrors: Array.from(errors), formUntouched: untouched, initialFormState: initialState});
    }

    optionTemplate = (opt: any, name: any) => {
      if (name !== ModifierType.ENCOUNTERS || !opt.value) {
        return opt.label;
      }
      const {visitCounts} = this.state;
      return <div className='p-clearfix'>
        {opt.label}
        &nbsp;<span style={styles.count}>{visitCounts[opt.value].toLocaleString()}</span>
      </div>;
    }

    renderInput(index: string, field: string, type) {
      const {values} = this.state.formState[index];
      switch (type) {
        case 'number':
          return <NumberInput style={{padding: '0 0.25rem', width: '3rem'}} value={values[field]}
            onChange={v => this.inputChange(index, field, v)}/>;
        case 'date':
          return <div style={styles.date}>
            <DatePicker
              value={values[field]}
              placeholder='YYYY-MM-DD'
              onChange={e => this.inputChange(index, field, e)}
              maxDate={new Date()}
            />
          </div>;
      }
    }

    render() {
      const {count, calculateError, formErrors, formState, formUntouched, initialFormState, loading} = this.state;
      const tooltip = `Dates are consistently shifted within a participant’s record
      by a time period of up to 364 days backwards to de-identify patient data.
      The date shift differs across participants.`;
      const disableCalculate = formErrors.length > 0 || formUntouched || initialFormState;
      return <div id='modifiers-form'>
        <h3 style={{...styles.header, marginTop: 0}}>Apply optional Modifiers</h3>
        <div style={{marginTop: '1rem'}}>
          <div>
            The following modifiers are optional and apply to all selected criteria
          </div>
          {calculateError && <div style={styles.error}>
            <ClrIcon style={{margin: '0 0.5rem 0 0.25rem'}} className='is-solid'
                     shape='exclamation-triangle' size='22'/>
            Sorry, the request cannot be completed. Please try again or contact Support in the left
            hand navigation.
          </div>}
          {formErrors.length > 0 && <div style={styles.errors}>
            {formErrors.map((err, e) => <div key={e} style={styles.errorItem}>
              {err}
            </div>)}
          </div>}
          {formState.map((mod, i) => {
            const {label, name, options, operator} = mod;
            return <div data-test-id={name} key={i} style={{marginTop: '0.75rem'}}>
              <label style={styles.label}>{label}</label>
              {name === ModifierType.EVENTDATE &&
              <TooltipTrigger content={<div>{tooltip}</div>}>
                <ClrIcon style={styles.info} className='is-solid' shape='info-standard'/>
              </TooltipTrigger>
              }
              <div style={styles.modifier}>
                <Dropdown value={operator}
                          style={styles.select}
                          onChange={(e) => this.selectChange(e.value, i)}
                          options={options}
                          optionValue='value'
                          itemTemplate={(e) => this.optionTemplate(e, name)}/>
                {operator && name !== ModifierType.ENCOUNTERS && <div style={{paddingTop: '1rem'}}>
                  {this.renderInput(i, '0', mod.type)}
                  {operator === Operator.BETWEEN && <React.Fragment>
                    <span style={{margin: '0 0.25rem'}}>and</span>
                    {this.renderInput(i, '1', mod.type)}
                  </React.Fragment>}
                </div>}
              </div>
            </div>;
          })}
          <CalculateFooter disabled={disableCalculate} calculating={loading}
                           calculate={() => this.calculate()} count={count}/>
          <FlexRowWrap style={{flexDirection: 'row-reverse', marginTop: '2rem'}}>
            <Button type='primary'
                    style={styles.addButton}
                    onClick={() => this.updateMods()}>
              APPLY MODIFIERS
            </Button>
            <Button type='link'
                    style={{color: colors.primary, marginRight: '0.5rem'}}
                    onClick={() => this.props.closeModifiers()}>
              BACK
            </Button>
          </FlexRowWrap>
        </div>
      </div>;
    }
  });
