// ui/src/app/cohort-review/query-report/query-report.component.ts
import {AfterContentChecked, ChangeDetectorRef, Component, OnInit} from '@angular/core';
import {cohortReviewStore} from 'app/cohort-review/review-state.service';
import {WorkspaceData} from 'app/resolvers/workspace';
import {CdrVersionStorageService} from 'app/services/cdr-version-storage.service';
import {WorkspaceData} from 'app/services/workspace-storage.service';
import {currentCohortStore, currentWorkspaceStore} from 'app/utils/navigation';
import {List} from 'immutable';
import {Observable} from 'rxjs/Observable';




@Component({
  selector: 'app-query-report',
  templateUrl: './query-report.component.html',
  styleUrls: ['./query-report.component.css']
})
export class QueryReportComponent implements OnInit, AfterContentChecked {
  cohort: any;
  review: any;
  cdrDetails: any ;
  data:  Observable<List<any>>;
  workspace: WorkspaceData;

  constructor(
    private cdref: ChangeDetectorRef,
    private cdrVersionStorageService: CdrVersionStorageService) {}

  ngOnInit() {
    this.cohort = currentCohortStore.getValue();
    this.workspace = currentWorkspaceStore.getValue();
    this.review = cohortReviewStore.getValue();
    this.cdrVersionStorageService.cdrVersions$.subscribe(resp => {
      this.cdrDetails = resp.items.find(v => v.cdrVersionId === this.workspace.cdrVersionId);
    });
  }

  ngAfterContentChecked() {
    this.cdref.detectChanges();
  }

  getDemoChartData(d) {
    this.ngAfterContentChecked();
    if (d) {
      this.data = d.toJS();
    }
  }
}

<div class="report-background">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-xs-6">
        <div class="container">
          <div class="row">
            <div class="col-sm-6 col-xs-6">
              <div class="query-title">
                Cohort Name
              </div>
              <div class="query-content">
                {{cohort.name}}
              </div>
              <div class="query-title">
                Created By
              </div>
              <div class="query-content">
                {{cohort.creator}}
              </div>
            </div>
            <div class="col-sm-6 col-xs-6">
              <div class="query-title">
                Date created
              </div>
              <div class="query-content">
                {{cohort.creationTime | date: 'yyyy-MM-dd': 'UTC/GMT'}}
              </div>
              <div class="query-title">
                CDR Version
              </div>
              <div class="query-content">
                {{cdrId}}
              </div>
            </div>
            <div class="col-sm-12 col-xs-12">
              <app-query-cohort-definition [cohort]="cohort" [review]="review"></app-query-cohort-definition>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-6">

        <!--Descriptive HTML Start-->
        <div>
          Descriptive Statistics:<br>
          <div style="width: 60%; border: 1px solid black;">
            <div class="container">
              <div class="row">
                <div class="col-sm-4"></div>
                <div class="col-sm-4">
                Total Count
                </div>
                <div class="col-sm-4">
                Percent of Cohort
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                Gender
                </div>
              </div>
              <div class="row">
                <div class="col-sm-4">
                  <div>Male</div>
                </div>
                <div class="col-sm-4">
                  1027
                </div>
                <div class="col-sm-4">
                  100%
                </div>
              </div>
            </div>
          </div>
        </div>

        <!--Descriptive HTML END-->
      </div>
    </div>
  </div>
  <app-overview-charts class="test-print"></app-overview-charts>
</div>

<!--<div class="container doNotPrint">-->
  <!--<div class="row header-border">-->
    <!--<div class="col-sm-1 col-xs-1 btn-margin">-->
      <!--<button-->
        <!--type="button"-->
        <!--class="btn btn-sm"-->
        <!--title="Go Back to the Participant Table"-->
        <!--[routerLink]="['../participants']">-->
        <!--<clr-icon shape="angle-double" dir="left"></clr-icon>-->
        <!--Participants-->
      <!--</button>-->
    <!--</div>-->
      <!--<h4 class="col-sm-11 col-xs-11">Cohort Query Report</h4>-->
  <!--</div>-->
<!--</div>-->

<!--<div class="report-background">-->
  <!--<div class="container">-->
    <!--<div class="row">-->
      <!--<div class="col-sm-10 col-xs-10">-->
        <!--Cohort name: {{cohort.name}} <br>-->
        <!--Created by: {{cohort.creator}} <br>-->
        <!--Date created: {{ cohort.creationTime | date: 'yyyy-MM-dd': 'UTC/GMT'}} <br><br>-->
      <!--</div>-->
      <!--<div class="col-sm-2 col-xs-2">-->
        <!--<clr-icon class="doNotPrint" shape="printer" size="48"></clr-icon>-->
        <!--<button class="doNotPrint btn btn-primary" (click)="onPrint()">PRINT REPORT</button>-->
      <!--</div>-->
    <!--</div>-->
  <!--</div>-->

<!--&lt;!&ndash;Cohort Definition HTML start&ndash;&gt;-->
  <!--Cohort Definition: <br>-->
  <!--<ng-container *ngFor="let group of definition; let g = index;">-->
    <!--<ng-container *ngFor="let item of group?.groups; let i = index">-->
     <!--<div *ngIf="i > 0">AND</div>-->
      <!--<div class="group-background">-->
        <!--<ng-container *ngFor="let param of item; let p = index;">-->
          <!--<div *ngIf="p > 0 ">OR</div>-->
          <!--<div style="border: 1px solid black;">-->
            <!--<ng-container *ngFor="let query of param; let s = index;">-->
              <!--<ng-container *ngIf="s > 0">-->
                <!--<div *ngIf="query?.type ==='DEMO'; else or ">AND</div>-->
                <!--<ng-template #or>OR</ng-template>-->
              <!--</ng-container>-->
            <!--<div>-->
              <!--{{query?.items}}-->
            <!--</div>-->
            <!--</ng-container>-->
          <!--</div>-->
        <!--</ng-container>-->
      <!--</div>-->
    <!--</ng-container>-->
  <!--</ng-container>-->
  <!--&lt;!&ndash;Cohort Definition HTML END&ndash;&gt;-->


<!--</div>-->

// ui/src/app/cohort-review/query-report/query-report.component.tsx
import {ComboChart} from 'app/cohort-common/combo-chart/combo-chart.component';
import {ParticipantsCharts} from 'app/cohort-review/participants-charts/participants-charts';
import {cohortReviewStore} from 'app/cohort-review/review-state.service';
import {SpinnerOverlay} from 'app/components/spinners';
import {cdrVersionsApi, cohortBuilderApi} from 'app/services/swagger-fetch-clients';
import {WorkspaceData} from 'app/services/workspace-storage.service';
import {withCurrentWorkspace} from 'app/utils';
import {currentCohortStore} from 'app/utils/navigation';
import {DomainType, SearchRequest} from 'generated/fetch';
import {fromJS} from 'immutable';
import * as React from 'react';

const css = `
  .container {
    min-width: 100%;
  }
  .report-background {
    background-color: white;
    padding-top: 1rem;
    margin-top: 0.5rem;
  }
  .report-background .query-title {
    font-size: 16px;
    font-weight: 600;
    color: #262262;
    line-height: 22px;
  }
  .report-background .query-content {
    font-size: 13px;
    color: black;
    line-height: 30px;
    padding-bottom: 0.6rem;
  }
  .header-border .btn-margin {
    margin-top : 0.7rem;
  }
  .temporal-container {
    padding-left: 1rem;
    margin-top: 1rem;
    margin-bottom: 1rem;
  }
  .stats-left-padding {
    padding-left: 6rem;
  }
  @media print{
    .doNotPrint{
      display:none !important;
      -webkit-print-color-adjust: exact;
    }
    .page-break {
      page-break-inside:auto;
    }
    .stats-left-padding {
      padding-left: 2rem;
    }
  }
`;

const domains = [DomainType[DomainType.CONDITION],
  DomainType[DomainType.PROCEDURE],
  DomainType[DomainType.DRUG],
  DomainType[DomainType.LAB]];

export interface QueryReportProps {
  workspace: WorkspaceData;
}
export interface QueryReportState {
  cdrName: string;
  data: any;
  loading: boolean;
}

export const QueryReport = withCurrentWorkspace()(
  class extends React.Component<QueryReportProps, QueryReportState> {
    cohort = currentCohortStore.getValue();
    review = cohortReviewStore.getValue();

    constructor(props: any) {
      super(props);
      this.state = {
        cdrName: null,
        data: null,
        loading: true
      };
    }

    componentDidMount() {
      const {cdrVersionId} = this.props.workspace;
      cdrVersionsApi().getCdrVersions().then(resp => {
        const cdrName = resp.items.find(
          v => v.cdrVersionId === this.review.cdrVersionId.toString()
        ).name;
        this.setState({cdrName});
      });
      const request = (JSON.parse(this.review.cohortDefinition)) as SearchRequest;
      cohortBuilderApi().getDemoChartInfo(+cdrVersionId, request)
        .then(response => {
          this.setState({data: fromJS((response).items), loading: false});
        });
    }

    render() {
      const {cdrName, data, loading} = this.state;
      return <React.Fragment>
        <style>{css}</style>
        <div className='report-background'>
          <div className='container'>
            <div className='row'>
              <div className='col-sm-6 col-xs-6'>
                <div className='container'>
                  <div className='row'>
                    <div className='col-sm-6 col-xs-6'>
                      <div className='query-title'>
                        Cohort Name
                      </div>
                      <div className='query-content'>
                        {this.review.cohortName}
                      </div>
                      <div className='query-title'>
                        Created By
                      </div>
                      <div className='query-content'>
                        {this.cohort.creator}
                      </div>
                    </div>
                    <div className='col-sm-6 col-xs-6'>
                      <div className='query-title'>
                        Date created
                      </div>
                      <div className='query-content'>
                        {this.cohort.creationTime}
                      </div>
                      <div className='query-title'>
                        Dataset
                      </div>
                      <div className='query-content'>
                        {cdrName}
                      </div>
                    </div>
                    <div className='col-sm-12 col-xs-12'>
                      // query-cohort-definition
                    </div>
                  </div>
                </div>
              </div>
              <div className=' col-sm-6 col-xs-6 stats-left-padding'>
                // app-descriptive-stats
              </div>
            </div>
          </div>
          // ov charts
          <div className='container container-margin'>
            <div className='row'>
              <div className='col-sm-12 col-xs-12'>
                <div className='container container-margin'>
                  <div className='row'>
                    <div className='col-sm-12 col-xs-12'>
                      <div>
                        <span className='chart-title'>Charts</span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className='container container-margin'>
                  <div className='row'>
                    <div className='col-sm-8 col-xs-8 col-lg-8 col-xl-8'>
                      <div className='chart-container'>
                        <div className='demography-title '>Demographics</div>
                        <div className='graph-border'>
                          <div className='demo-chart-heading'>
                            Participants by Gender, Age Range & Race
                          </div>
                          {data && <ComboChart mode={'stacked'} data={data} />}
                          {loading && <SpinnerOverlay />}
                        </div>
                      </div>
                    </div>
                    <div className='col-sm-10 col-xs-10 col-lg-10 col-xl-10'>
                      <div className='chart-container'>
                        {domains.map((domain, i) => (
                          <div key={i}>
                            <ParticipantsCharts domain={domain}/>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </React.Fragment>;
    }
  }
);
