// ui/src/app/cohort-search/search-bar/search-bar.component.ts
import {Component, EventEmitter, HostListener, Input, OnDestroy, OnInit, Output, ViewChild} from '@angular/core';
import {FormControl} from '@angular/forms';
import {autocompleteStore, subtreePathStore, subtreeSelectedStore} from 'app/cohort-search/search-state.service';
import {domainToTitle} from 'app/cohort-search/utils';
import {cohortBuilderApi} from 'app/services/swagger-fetch-clients';
import {triggerEvent} from 'app/utils/analytics';
import {currentWorkspaceStore} from 'app/utils/navigation';
import {CriteriaType, DomainType} from 'generated/fetch';
import {Subscription} from 'rxjs/Subscription';

const trigger = 3;

@Component({
  selector: 'app-list-search-bar',
  templateUrl: './search-bar.component.html',
  styleUrls: ['./search-bar.component.css']
})
export class SearchBarComponent implements OnInit, OnDestroy {
  @Input() node: any;
  @Output() ingredients = new EventEmitter<any>();
  searchTerm: FormControl = new FormControl();
  typedTerm: string;
  options = [];
  loading = false;
  noResults = false;
  optionSelected = false;
  error = false;
  subscription: Subscription;
  highlightedOption: number;
  subtype: string;

  @ViewChild('searchBar') searchBar;
  @HostListener('document:mouseup', ['$event.target'])
  onClick(targetElement) {
    const clickedInside = this.searchBar.nativeElement.contains(targetElement);
    if (!clickedInside) {
      this.hideDropdown();
    }
  }

  ngOnInit() {
    this.subscription = autocompleteStore.subscribe(searchTerm => {
      this.searchTerm.setValue(searchTerm, {emitEvent: false});
    });
    this.subscription.add(this.searchTerm.valueChanges
      .debounceTime(300)
      .distinctUntilChanged()
      .subscribe( value => {
        if (this.node.domainId === DomainType.PHYSICALMEASUREMENT) {
          triggerEvent(`Cohort Builder Search - Physical Measurements`, 'Search', value);
          autocompleteStore.next(value);
        } else {
          if (value.length >= trigger) {
            triggerEvent(
              `Cohort Builder Search - ${domainToTitle(this.node.domainId)}`,
              'Search',
              value
            );
            this.inputChange();
          } else {
            this.options = [];
            this.noResults = false;
          }
        }
      })
    );
  }

  ngOnDestroy() {
    this.subscription.unsubscribe();
  }

  inputChange() {
    this.typedTerm = this.searchTerm.value;
    this.loading = true;
    this.optionSelected = false;
    this.noResults = false;
    const cdrId = +(currentWorkspaceStore.getValue().cdrVersionId);
    const {domainId, isStandard, type} = this.node;
    const apiCall = domainId === DomainType.DRUG
      ? cohortBuilderApi().findDrugBrandOrIngredientByValue(cdrId, this.searchTerm.value)
      : cohortBuilderApi().findCriteriaAutoComplete(
        cdrId, domainId, this.searchTerm.value, type, isStandard
      );
    apiCall.then(resp => {
      this.options = [];
      this.noResults = resp.items.length === 0;
      const optionNames: Array<string> = [];
      this.highlightedOption = null;
      resp.items.forEach(option => {
        if (optionNames.indexOf(option.name) === -1) {
          optionNames.push(option.name);
          this.options.push(option);
        }
      });
      this.loading = false;
    }, (err) => this.error = err);
  }

  get showOverflow() {
    return this.options && this.options.length <= 10;
  }

  selectOption(option: any) {
    if (option) {
      this.optionSelected = true;
      this.searchTerm.reset('');
      this.searchTerm.setValue(option.name, {emitEvent: false});
      if (option.type === CriteriaType[CriteriaType.BRAND]) {
        const cdrId = +(currentWorkspaceStore.getValue().cdrVersionId);
        cohortBuilderApi().findDrugIngredientByConceptId(cdrId, option.conceptId)
          .then(resp => {
            if (resp.items.length) {
              const ingredients = resp.items.map(it => it.name);
              this.ingredients.emit(ingredients);
              // just grabbing the first one on the list for now
              const {path, id} = resp.items[0];
              subtreePathStore.next(path.split('.'));
              subtreeSelectedStore.next(id);
            }
          });
      } else {
        this.ingredients.emit(null);
        autocompleteStore.next(option.name);
        subtreePathStore.next(option.path.split('.'));
        subtreeSelectedStore.next(option.id);
      }
    }
  }

  hideDropdown() {
    this.options = [];
  }

  moveUp() {
    if (this.highlightedOption === 0) {
      this.highlightedOption = null;
      this.searchTerm.setValue(this.typedTerm, {emitEvent: false});
    } else if (this.highlightedOption > 0) {
      this.highlightedOption--;
      this.searchTerm.setValue(this.options[this.highlightedOption].name, {emitEvent: false});
    }
  }

  moveDown() {
    if (this.highlightedOption === null) {
      this.highlightedOption = 0;
      this.searchTerm.setValue(this.options[this.highlightedOption].name, {emitEvent: false});
    } else if ((this.highlightedOption + 1) < this.options.length) {
      this.highlightedOption++;
      this.searchTerm.setValue(this.options[this.highlightedOption].name, {emitEvent: false});
    }
  }

  enterSelect() {
    this.selectOption(this.options[this.highlightedOption]);
  }
}

<div #searchBar class="dropdown" [class.open]="options.length || noResults">
  <div class="search-box">
    <clr-icon *ngIf="!loading" shape="search"></clr-icon>
    <span *ngIf="loading" class="spinner spinner-inline"></span>
    <input clrInput
     class="no-border"
     type="text"
     name="searchTerm"
     autocomplete="off"
     (keyup.enter)="enterSelect()"
     (keyup.arrowup)="moveUp()"
     (keyup.arrowdown)="moveDown()"
     [formControl]="searchTerm"/>
  </div>
  <div *ngIf="noResults" class="dropdown-menu">
    <button class="dropdown-item disabled">
      <em>No results based on your search</em>
    </button>
  </div>
  <div *ngIf="ingredientList.length" class="match-container">Ingredients in this brand: {{ingredientList.join(', ')}} </div>
  <div *ngIf="numMatches > 1 && !ingredientList.length" class="match-container">
    {{searchTerm.value}} exists {{numMatches}} times in the tree below
  </div>
  <div *ngIf="options.length" class="dropdown-menu" [class.overflow]="showOverflow">
    <app-option-info
      *ngFor="let option of options; let i = index"
      [option]="option"
      [highlighted]="i === highlightedOption"
      [searchTerm]="searchTerm.value"
      (click)="selectOption(option)">
    </app-option-info>
  </div>
</div>

// ui/src/app/cohort-search/search-bar/search-bar.component.tsx
import * as fp from 'lodash/fp';
import * as React from 'react';

import {autocompleteStore, subtreePathStore, subtreeSelectedStore} from 'app/cohort-search/search-state.service';
import {domainToTitle} from 'app/cohort-search/utils';
import {ClrIcon} from 'app/components/icons';
import {TextInput} from 'app/components/inputs';
import {TooltipTrigger} from 'app/components/popups';
import {cohortBuilderApi} from 'app/services/swagger-fetch-clients';
import colors, {colorWithWhiteness} from 'app/styles/colors';
import {highlightSearchTerm, reactStyles} from 'app/utils';
import {triggerEvent} from 'app/utils/analytics';
import {currentWorkspaceStore} from 'app/utils/navigation';
import {Criteria, CriteriaType, DomainType} from 'generated/fetch';
import {AutoComplete} from 'primereact/autocomplete';
import {Subscription} from 'rxjs/Subscription';

const styles = reactStyles({
  searchContainer: {
    position: 'absolute',
    width: '95%',
    padding: '0.4rem 0',
    background: colors.white,
    zIndex: 10,
  },
  searchBar: {
    height: '40px',
    width: '100%',
    padding: '7px 14px',
    borderRadius: '5px',
    backgroundColor: colorWithWhiteness(colors.secondary, 0.8),
  },
  searchInput: {
    width: '85%',
    height: '1rem',
    marginLeft: '0.25rem',
    padding: '0',
    background: 'transparent',
    border: 0,
    outline: 'none',
  },
});

const trigger = 3;

interface OptionProps {
  option: any;
  searchTerm: string;
  highlighted: boolean;
}

interface OptionState {
  truncated: boolean;
}

class SearchBarOption extends React.Component<OptionProps, OptionState> {
  container: HTMLButtonElement;
  constructor(props: OptionProps) {
    super(props);
    this.state = {truncated: false};
  }

  handleResize = fp.debounce(100, () => {
    this.checkContainerWidth();
  });

  componentDidMount(): void {
    this.checkContainerWidth();
    window.addEventListener('resize', this.handleResize);
  }

  componentWillUnmount(): void {
    window.removeEventListener('resize', this.handleResize);
  }

  checkContainerWidth() {
    const {offsetWidth, scrollWidth} = this.container;
    this.setState({truncated: scrollWidth > offsetWidth});
  }
  render() {
    const {option: {name}, searchTerm} = this.props;
    const displayText = highlightSearchTerm(searchTerm, name, colors.success);
    return <button className='dropdown-item'ref={(e) => this.container = e}>
      <TooltipTrigger content={<div>{displayText}</div>} disabled={!this.state.truncated}>
        <div>{displayText}</div>
      </TooltipTrigger>
    </button>;
  }
}

interface Props {
  setIngredients: Function;
  node: Criteria;
}

interface State {
  searchTerm: string;
  typedTerm: string;
  options: Array<any>;
  loading: boolean;
  noResults: boolean;
  optionSelected: boolean;
  error: boolean;
  highlightedOption: number;
  subtype: string;
}

export class SearchBar extends React.Component<Props, State> {
  subscription: Subscription;
  constructor(props: Props) {
    super(props);
    this.state = {
      searchTerm: undefined,
      typedTerm: undefined,
      options: [],
      loading: false,
      noResults: false,
      optionSelected: false,
      error: false,
      highlightedOption: undefined,
      subtype: undefined,
    };
  }

  debounceInput = fp.debounce(300, (input: string) => {
    console.log(input);
    if (input.length < trigger) {
      this.setState({options: [], noResults: false});
    } else {
      this.handleInput();
    }
  });

  componentDidMount() {
    this.subscription = autocompleteStore.subscribe(searchTerm => {
      this.setState({searchTerm});
    });
  }

  componentWillUnmount() {
    this.subscription.unsubscribe();
  }

  onInputChange(value: string) {
    console.log(value);
    const {node: {domainId}} = this.props;
    autocompleteStore.next(value);
    if (domainId === DomainType.PHYSICALMEASUREMENT.toString()) {
      triggerEvent(`Cohort Builder Search - Physical Measurements`, 'Search', value);
      autocompleteStore.next(value);
    } else {
      this.debounceInput(value);
    }
  }

  handleInput() {
    const {node: {domainId, isStandard, type}} = this.props;
    const {searchTerm} = this.state;
    triggerEvent(`Cohort Builder Search - ${domainToTitle(domainId)}`, 'Search', searchTerm);
    this.setState({loading: true, optionSelected: false, noResults: false});
    const {cdrVersionId} = currentWorkspaceStore.getValue();
    const apiCall = domainId === DomainType.DRUG.toString()
      ? cohortBuilderApi().findDrugBrandOrIngredientByValue(+cdrVersionId, searchTerm)
      : cohortBuilderApi().findCriteriaAutoComplete(+cdrVersionId, domainId, searchTerm, type, isStandard);
    apiCall.then(resp => {
      const optionNames: Array<string> = [];
      const options = resp.items.filter(option => {
        if (!optionNames.includes(option.name)) {
          optionNames.push(option.name);
          return true;
        }
        return false;
      });
      this.setState({highlightedOption: null, loading: false, noResults: options.length === 0, options});
    }, (err) => this.setState({error: err}));
  }

  get showOverflow() {
    const {options} = this.state;
    return options && options.length <= 10;
  }

  selectOption(option: any) {
    if (option) {
      const {setIngredients} = this.props;
      this.setState({optionSelected: true, searchTerm: option.name});
      if (option.type === CriteriaType[CriteriaType.BRAND]) {
        const cdrId = +(currentWorkspaceStore.getValue().cdrVersionId);
        cohortBuilderApi().findDrugIngredientByConceptId(cdrId, option.conceptId)
          .then(resp => {
            if (resp.items.length) {
              const ingredients = resp.items.map(it => it.name);
              setIngredients(ingredients);
              // just grabbing the first one on the list for now
              const {path, id} = resp.items[0];
              subtreePathStore.next(path.split('.'));
              subtreeSelectedStore.next(id);
            }
          });
      } else {
        setIngredients(null);
        autocompleteStore.next(option.name);
        subtreePathStore.next(option.path.split('.'));
        subtreeSelectedStore.next(option.id);
      }
    }
  }

  enterSelect() {
    const {highlightedOption, options} = this.state;
    this.selectOption(options[highlightedOption]);
  }

  render() {
    const {node} = this.props;
    const {highlightedOption, options, searchTerm} = this.state;
    return <div>
      <div style={styles.searchContainer}>
        <div style={styles.searchBar}>
          <ClrIcon shape='search' size='18'/>
          <TextInput style={styles.searchInput} value={searchTerm} onChange={(e) => this.onInputChange(e)} />
        </div>
        {/*<AutoComplete field='name' value={searchTerm} onChange={(e) => this.onInputChange(e.value)}*/}
        {/*  suggestions={options} onSelect={(e) => this.selectOption(e.value)} completeMethod={() => this.inputChange()}/>*/}
      </div>
      {options.length && <div className='dropdown-menu'>
        {options.map((opt, o) => <SearchBarOption key={o}
                                            option={opt}
                                            searchTerm={searchTerm}
                                            highlighted={o === highlightedOption}/>)}
      </div>}
    </div>;
  }
}
