// ui/src/app/cohort-search/search-group/search-group.component.tsx
import {InputSwitch} from 'primereact/inputswitch';
import {Menu} from 'primereact/menu';
import {TieredMenu} from 'primereact/tieredmenu';
import * as React from 'react';

import {SearchGroupItem} from 'app/cohort-search/search-group-item/search-group-item.component';
import {criteriaMenuOptionsStore, searchRequestStore, wizardStore} from 'app/cohort-search/search-state.service';
import {domainToTitle, generateId, mapGroup, typeToTitle} from 'app/cohort-search/utils';
import {Clickable} from 'app/components/buttons';
import {ClrIcon} from 'app/components/icons';
import {TooltipTrigger} from 'app/components/popups';
import {RenameModal} from 'app/components/rename-modal';
import {Spinner} from 'app/components/spinners';
import {cohortBuilderApi} from 'app/services/swagger-fetch-clients';
import colors, {colorWithWhiteness} from 'app/styles/colors';
import {reactStyles, withCurrentWorkspace} from 'app/utils';
import {triggerEvent} from 'app/utils/analytics';
import {isAbortError} from 'app/utils/errors';
import {WorkspaceData} from 'app/utils/workspace-data';
import {DomainType, ResourceType, SearchRequest, TemporalMention, TemporalTime} from 'generated/fetch';

const styles = reactStyles({
  card: {
    background: colors.white,
    borderColor: 'rgba(215, 215, 215, 0.5)',
    borderRadius: '0.2rem',
    boxShadow: `0 0.125rem 0.125rem 0 ${colorWithWhiteness(colors.black, 0.85)}`,
    margin: '0 0 0.6rem'
  },
  cardBlock: {
    borderBottom: `1px solid ${colors.light}`,
    padding: '0.5rem 0.5rem 0.5rem 0.75rem'
  },
  cardHeader: {
    backgroundColor: colorWithWhiteness(colors.light, -0.3),
    color: colors.primary,
    fontSize: '14px',
    fontWeight: 600,
    minWidth: '100%',
    padding: '0.5rem 0.75rem'
  },
  overlay: {
    background: colors.white,
    display: 'table',
    opacity: 0.9,
    position: 'relative',
    textAlign: 'center',
    verticalAlign: 'middle',
  },
  overlayInner: {
    color: colors.warning,
    display: 'table-cell',
    fontSize: '18px',
    verticalAlign: 'middle',
  },
  overlayButton: {
    background: 'transparent',
    border: 0,
    color: colors.accent,
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 600,
    letterSpacing: 0,
    margin: '0.25rem 0',
  },
  itemOr: {
    background: colors.white,
    color: colorWithWhiteness(colors.black, 0.75),
    float: 'right',
    marginRight: '46%',
    padding: '0 10px'
  },
  menu: {
    maxWidth: '15rem',
    minWidth: '5rem',
    width: 'auto'
  },
  searchItem: {
    borderBottom: `1px solid ${colorWithWhiteness(colors.black, 0.75)}`,
    margin: '0 0.5rem',
    padding: '0.5rem 0.25rem'
  },
  menuButton: {
    border: `1px solid ${colorWithWhiteness(colors.black, 0.75)}`,
    borderRadius: '0.125rem',
    color: colorWithWhiteness(colors.black, 0.45),
    fontSize: '12px',
    fontWeight: 100,
    height: '1.5rem',
    letterSpacing: '1px',
    lineHeight: '1.5rem',
    padding: '0 0.5rem',
    textTransform: 'uppercase',
    verticalAlign: 'middle'
  },
  row: {
    display: 'flex',
    flexWrap: 'wrap',
    marginLeft: '-0.5rem',
    marginRight: '-0.5rem',
  },
  col6: {
    flex: '0 0 50%',
    maxWidth: '50%',
    padding: '0 0.25rem',
  },
  timeInput: {
    border: `1px solid ${colorWithWhiteness(colors.black, 0.75)}`,
    borderRadius: '0.1rem',
    height: '1.4rem',
    marginLeft: '0.5rem',
    verticalAlign: 'middle',
    width: '3rem'
  },
  inputError: {
    background: colorWithWhiteness(colors.danger, 0.85),
    border: `1px solid ${colorWithWhiteness(colors.danger, 0.6)}`,
    borderRadius: '3px',
    color: colorWithWhiteness(colors.dark, .1),
    fontSize: '11px',
    lineHeight: '16px',
    marginBottom: '0.25rem',
    padding: '5px 3px'
  }
});

const css = `
  .p-inputswitch.p-disabled > .p-inputswitch-slider {
    cursor: not-allowed;
  }
  body .p-menuitem > .p-menuitem-link {
    height: 1.25rem;
    line-height: 1.25rem;
    padding: 0 1rem;
  }
  body .p-menuitem.menuitem-header > .p-menuitem-link {
    font-size: 12px;
    font-weight: 600;
    height: auto;
    line-height: 0.75rem;
    padding-left: 0.5rem;
  }
  body .p-tieredmenu .p-menu-separator {
    margin: 0.25rem 0;
  }
  body .p-tieredmenu .p-submenu-list {
    padding: 0.5rem 0;
    width: 10rem;
  }
`;

const temporalMentions = [
  TemporalMention.ANYMENTION,
  TemporalMention.FIRSTMENTION,
  TemporalMention.LASTMENTION
];

const temporalTimes = [
  TemporalTime.DURINGSAMEENCOUNTERAS,
  TemporalTime.XDAYSAFTER,
  TemporalTime.XDAYSBEFORE,
  TemporalTime.WITHINXDAYSOF
];

function temporalEnumToText(option) {
  switch (option) {
    case TemporalMention.ANYMENTION:
      return 'Any mention of';
    case TemporalMention.FIRSTMENTION:
      return 'First mention of';
    case TemporalMention.LASTMENTION:
      return 'Last mention of';
    case TemporalTime.DURINGSAMEENCOUNTERAS:
      return 'During same encounter as';
    case TemporalTime.XDAYSBEFORE:
      return 'X or more days before';
    case TemporalTime.XDAYSAFTER:
      return 'X or more days after';
    case TemporalTime.WITHINXDAYSOF:
      return 'On or within X days of';
  }
}

function initItem(id: string, type: string, tempGroup: number) {
  return {
    id,
    type,
    searchParameters: [],
    modifiers: [],
    temporalGroup: tempGroup,
    status: 'active'
  };
}

interface Props {
  dataFilters: Array<string>;
  group: any;
  index: number;
  role: keyof SearchRequest;
  updated: number;
  updateRequest: Function;
  workspace: WorkspaceData;
}

interface State {
  count: number;
  criteriaMenuOptions: any;
  error: boolean;
  initializing: boolean;
  inputError: boolean;
  inputTouched: boolean;
  loading: boolean;
  overlayStyle: any;
  renaming: boolean;
}

export const SearchGroup = withCurrentWorkspace()(
  class extends React.Component<Props, State> {
    private aborter = new AbortController();
    private criteriaMenu: any;
    private deleteTimeout: NodeJS.Timeout;
    private groupMenu: any;
    private mentionMenu: any;
    private temporalCriteriaMenu: any;
    private timeMenu: any;

    constructor(props: any) {
      super(props);
      this.state = {
        count: undefined,
        criteriaMenuOptions: {programTypes: [], domainTypes: []},
        error: false,
        initializing: true,
        inputError: false,
        inputTouched: false,
        loading: false,
        overlayStyle: undefined,
        renaming: false
      };
    }

    componentDidMount(): void {
      const {group: {id}, updateRequest, workspace: {cdrVersionId}} = this.props;
      criteriaMenuOptionsStore.subscribe(options => {
        if (!!options[cdrVersionId]) {
          this.setState({criteriaMenuOptions: options[cdrVersionId]});
        }
      });
      if (typeof ResizeObserver === 'function') {
        const groupDiv = document.getElementById(id);
        // check that groupDiv is of type Element
        if (groupDiv && groupDiv.tagName) {
          // create observer to reposition overlays on div resize
          const ro = new ResizeObserver(() => {
            const {status} = this.props.group;
            if (status === 'hidden' || status === 'pending') {
              this.setOverlayPosition();
            }
          });
          ro.observe(groupDiv);
        }
      }
      updateRequest();
      this.getGroupCount();
    }

    componentDidUpdate(prevProps: Readonly<Props>): void {
      const {dataFilters} = this.props;
      if (prevProps.dataFilters !== dataFilters) {
        this.setState({initializing: true});
        this.getGroupCount();
      }
    }

    componentWillUnmount(): void {
      this.aborter.abort();
      clearTimeout(this.deleteTimeout);
    }

    getGroupCount() {
      this.abortPendingCalls();
      this.setState({error: false, loading: true});
      const {dataFilters, group, role, workspace: {cdrVersionId}} = this.props;
      const mappedGroup = mapGroup(group);
      const request = {
        includes: [],
        excludes: [],
        dataFilters,
        [role]: [mappedGroup]
      };
      cohortBuilderApi().countParticipants(+cdrVersionId, request, {signal: this.aborter.signal})
        .then(count => this.setState({count, initializing: false, loading: false}))
        .catch(error => {
          if (!isAbortError(error)) {
            console.error(error);
            this.setState({error: true, loading: false});
          }
        });
    }

    abortPendingCalls() {
      if (this.state.loading) {
        this.aborter.abort();
        this.aborter = new AbortController();
      }
    }

    update() {
      const {group: {temporal}, updateRequest} = this.props;
      // Prevent multiple group count calls when loading an existing cohort
      if (!this.state.initializing) {
        updateRequest();
        if (this.hasActiveItems && (!temporal || !this.temporalError)) {
          this.getGroupCount();
        }
      }
    }

    get hasActiveItems() {
      return this.props.group.items.some(it => it.status === 'active');
    }

    get items() {
      const {group: {items, temporal}} = this.props;
      return !temporal ? items : items.filter(it => it.temporalGroup === 0);
    }

    get temporalItems() {
      const {group: {items}} = this.props;
      return items.filter(it => it.temporalGroup === 1);
    }

    get disableTemporal() {
      return this.items.some(it => [DomainType.PHYSICALMEASUREMENT, DomainType.PERSON, DomainType.SURVEY].includes(it.type));
    }

    remove() {
      triggerEvent('Delete', 'Click', 'Snowman - Delete Group - Cohort Builder');
      this.hide('pending');
      this.deleteTimeout = setTimeout(() => {
        this.removeGroup();
      }, 10000);
    }

    hide(status: string) {
      triggerEvent('Suppress', 'Click', 'Snowman - Suppress Group - Cohort Builder');
      this.setGroupProperty('status', status);
      setTimeout(() => this.setOverlayPosition());
    }

    enable() {
      triggerEvent('Enable', 'Click', 'Enable - Suppress Group - Cohort Builder');
      this.setGroupProperty('status', 'active');
      this.setState({overlayStyle: undefined});
    }

    undo() {
      triggerEvent('Undo', 'Click', 'Undo - Delete Group - Cohort Builder');
      clearTimeout(this.deleteTimeout);
      this.enable();
    }

    removeGroup() {
      const {group, role} = this.props;
      const searchRequest = searchRequestStore.getValue();
      searchRequest[role] = searchRequest[role].filter(grp => grp.id !== group.id);
      searchRequestStore.next(searchRequest);
    }

    rename(newName: string) {
      const {group, index, role} = this.props;
      const searchRequest = searchRequestStore.getValue();
      searchRequest[role][index] = {...group, name: newName};
      searchRequestStore.next(searchRequest);
      this.setState({renaming: false});
    }

    setOverlayPosition() {
      const {group} = this.props;
      const groupCard = document.getElementById(group.id);
      if (groupCard) {
        const {marginBottom, width, height} = window.getComputedStyle(groupCard);
        const margin = `-${(parseFloat(height) + parseFloat(marginBottom))}px 0 ${marginBottom}`;
        this.setState({overlayStyle: {height, margin, width}});
      }
    }

    launchWizard(criteria: any, temporalGroup: number) {
      this.criteriaMenu.hide();
      const {group, role} = this.props;
      const {domain, type, standard} = criteria;
      if (temporalGroup === 1) {
        triggerEvent('Temporal', 'Click', `${domainToTitle(domain)} - Temporal - Cohort Builder`);
      } else {
        const category = `${role === 'includes' ? 'Add' : 'Excludes'} Criteria`;
        // If domain is PERSON, list the type as well as the domain in the label
        const label = `${domainToTitle(domain)} ${(domain === DomainType.PERSON ? `- ${typeToTitle(type)}` : '')} - Cohort Builder`;
        triggerEvent(category, 'Click', `${category} - ${label}`);
      }
      const itemId = generateId('items');
      const item = initItem(itemId, domain, temporalGroup);
      const groupId = group.id;
      const context = {item, domain, type, standard, role, groupId, itemId, temporalGroup};
      wizardStore.next(context);
    }

    setGroupProperty(property: string, value: any) {
      const {group, role, updateRequest} = this.props;
      const searchRequest = searchRequestStore.getValue();
      const groupIndex = searchRequest[role].findIndex(grp => grp.id === group.id);
      if (groupIndex > -1) {
        searchRequest[role][groupIndex][property] = value;
        searchRequestStore.next(searchRequest);
        updateRequest();
      }
    }

    handleTemporalChange(e: any) {
      const {value} = e.target;
      triggerEvent('Temporal', 'Click', 'Turn On Off - Temporal - Cohort Builder');
      this.setGroupProperty('temporal', value);
      if ((!value && this.hasActiveItems) || (value && !this.temporalError)) {
        this.getGroupCount();
      }
    }

    setMention(mention: TemporalMention) {
      if (mention !== this.props.group.mention) {
        triggerEvent('Temporal', 'Click', `${temporalEnumToText(mention)} - Temporal - Cohort Builder`);
        this.setGroupProperty('mention', mention);
        if (!this.temporalError) {
          this.getGroupCount();
        }
      }
    }

    setTime(time: TemporalTime) {
      triggerEvent('Temporal', 'Click', `${temporalEnumToText(time)} - Temporal - Cohort Builder`);
      this.setGroupProperty('time', time);
      if (!this.temporalError) {
        this.getGroupCount();
      }
    }

    setTimeValue(timeValue: string) {
      const timeValueInt = parseInt(timeValue, 10);
      this.setState({inputError: isNaN(timeValueInt) || timeValueInt < 0, inputTouched: true});
      this.setGroupProperty('timeValue', timeValue);
      if (!this.temporalError) {
        this.getGroupCount();
      }
    }

    get temporalError() {
      const {group: {items, time, timeValue}} = this.props;
      const counts = items.reduce((acc, it) => {
        if (it.status === 'active') {
          acc[it.temporalGroup]++;
        }
        return acc;
      }, [0, 0]);
      const inputError = time !== TemporalTime.DURINGSAMEENCOUNTERAS && isNaN(parseInt(timeValue, 10));
      return counts.includes(0) || inputError;
    }

    mapCriteriaMenuItem(domain: any, temporalGroup: number) {
      if (!!domain.children) {
        return {label: domain.name, items: domain.children.map((dt) => this.mapCriteriaMenuItem(dt, temporalGroup))};
      }
      return {label: domain.name, command: () => this.launchWizard(domain, temporalGroup)};
    }

    get criteriaMenuItems() {
      const {criteriaMenuOptions: {domainTypes, programTypes}} = this.state;
      return this.props.group.temporal
        ? domainTypes.map((dt) => this.mapCriteriaMenuItem(dt, 0))
        : [
          {label: 'Program Data', className: 'menuitem-header'},
          ...programTypes.map((dt) => this.mapCriteriaMenuItem(dt, 0)),
          {separator: true},
          {label: 'Domains', className: 'menuitem-header'},
          ...domainTypes.map((dt) => this.mapCriteriaMenuItem(dt, 0))
        ];
    }

    get temporalCriteriaMenuItems() {
      return this.state.criteriaMenuOptions.domainTypes.map((dt) => this.mapCriteriaMenuItem(dt, 1));
    }

    get mentionMenuItems() {
      return temporalMentions.map(tm => ({label: temporalEnumToText(tm), command: () => this.setMention(tm)}));
    }

    get timeMenuItems() {
      return temporalTimes.map(tt => ({label: temporalEnumToText(tt), command: () => this.setTime(tt)}));
    }

    get groupMenuItems() {
      return [
        {label: 'Edit group name', command: () => this.setState({renaming: true})},
        {label: 'Suppress group from total count', command: () => this.hide('hidden')},
        {label: 'Delete group', command: () => this.remove()},
      ];
    }

    get groupErrorText() {
      if (this.state.error) {
        return 'Sorry, the request cannot be completed. Please try again or contact Support in the left hand navigation.';
      }
      if (!this.hasActiveItems) {
        return 'All criteria in this group are suppressed. Un-suppress criteria to update the group count based on the visible criteria.';
      }
      if (this.props.group.temporal && this.temporalError) {
        return 'Please complete criteria selections before saving temporal relationship.';
      }
      return '';
    }

    get existingGroupNames() {
      const {group, role} = this.props;
      const searchRequest = searchRequestStore.getValue();
      return searchRequest[role]
        .filter(grp => grp.id !== group.id && !!grp.name)
        .map(grp => grp.name);
    }

    render() {
      const {dataFilters, group: {id, items, mention, name, status, temporal, time, timeValue}, index, role} = this.props;
      const {count, error, inputError, inputTouched, loading, overlayStyle, renaming} = this.state;
      const groupName = !!name ? name : `Group ${index + 1}`;
      const showGroupCount = !loading && !error && this.hasActiveItems && (!temporal || !this.temporalError) && count !== undefined;
      const showGroupError = error || !this.hasActiveItems || (temporal && this.temporalError);
      return <React.Fragment>
        <style>{css}</style>
        <div id={id} style={styles.card}>
          {/* Group Header */}
          <div style={styles.cardHeader}>
            <Menu style={styles.menu}
              appendTo={document.body}
              model={this.groupMenuItems}
              popup
              ref={el => this.groupMenu = el} />
            <Clickable style={{display: 'inline-block', paddingRight: '0.5rem'}}onClick={(e) => this.groupMenu.toggle(e)}>
              <ClrIcon style={{color: colors.accent}} shape='ellipsis-vertical'/>
            </Clickable>
            {groupName}
          </div>
          {/* Temporal mention dropdown */}
          {temporal && <div style={styles.cardBlock}>
            <Menu style={styles.menu}
              appendTo={document.body}
              model={this.mentionMenuItems}
              popup
              ref={el => this.mentionMenu = el} />
            <button style={styles.menuButton} onClick={(e) => this.mentionMenu.toggle(e)}>
              {temporalEnumToText(mention)} <ClrIcon shape='caret down' size={12}/>
            </button>
          </div>}
          {/* Main search item list/temporal group 0 items */}
          {this.items.map((item, i) => <div key={i} data-test-id='item-list' style={styles.searchItem}>
            <SearchGroupItem dataFilters={dataFilters}
              role={role}
              groupId={id}
              item={item}
              index={i}
              updateGroup={() => this.update()}/>
            {status === 'active' && <div style={styles.itemOr}>OR</div>}
          </div>)}
          {/* Criteria menu for main search item list/temporal group 0 items */}
          <div style={styles.cardBlock}>
            <TieredMenu style={{...styles.menu, padding: '0.5rem 0'}}
              appendTo={document.body}
              model={this.criteriaMenuItems}
              popup
              ref={el => this.criteriaMenu = el} />
            <button style={styles.menuButton} onClick={(e) => this.criteriaMenu.toggle(e)}>
              Add Criteria <ClrIcon shape='caret down' size={12}/>
            </button>
          </div>
          {temporal && <React.Fragment>
            {/* Temporal time dropdown */}
            <div style={styles.cardBlock}>
              {time !== TemporalTime.DURINGSAMEENCOUNTERAS && inputError && inputTouched && <div style={styles.inputError}>
                Please enter a positive number
              </div>}
              <Menu style={styles.menu}
                appendTo={document.body}
                model={this.timeMenuItems}
                popup
                ref={el => this.timeMenu = el} />
              <button style={styles.menuButton} onClick={(e) => this.timeMenu.toggle(e)}>
                {temporalEnumToText(time)} <ClrIcon shape='caret down' size={12}/>
              </button>
              {time !== TemporalTime.DURINGSAMEENCOUNTERAS &&
                <input style={styles.timeInput} type='number' value={timeValue} min={0}
                  onChange={(v) => this.setTimeValue(v.target.value)}/>
              }
            </div>
            {/* Temporal group 1 items */}
            {this.temporalItems.map((item, i) => <div key={i} style={styles.searchItem} data-test-id='temporal-item-list'>
              <SearchGroupItem dataFilters={dataFilters}
                role={role}
                groupId={id}
                item={item}
                index={i}
                updateGroup={() => this.update()}/>
              {status === 'active' && <div style={styles.itemOr}>OR</div>}
            </div>)}
            {/* Criteria menu for temporal group 1 items */}
            <div style={styles.cardBlock}>
              <Menu style={styles.menu} appendTo={document.body} model={this.temporalCriteriaMenuItems}
                popup ref={el => this.temporalCriteriaMenu = el} />
              <button style={styles.menuButton} onClick={(e) => this.temporalCriteriaMenu.toggle(e)}>
                Add Criteria <ClrIcon shape='caret down' size={12}/>
              </button>
            </div>
          </React.Fragment>}
          {/* Group footer */}
          {!!items.length && <div style={styles.cardHeader}>
            <div style={this.disableTemporal ? {...styles.row, cursor: 'not-allowed'} : styles.row}>
              <div style={{...styles.col6, display: 'flex'}}>
                <InputSwitch
                  checked={temporal}
                  disabled={this.disableTemporal}
                  onChange={(e) => this.handleTemporalChange(e)}/>
                <div style={{paddingLeft: '0.5rem'}}>Temporal</div>
              </div>
              <div style={{...styles.col6, textAlign: 'right'}}>
                <div>
                  Group Count:&nbsp;
                  {loading && (!temporal || !this.temporalError) && <Spinner size={16}/>}
                  {showGroupCount && <span>
                    {count.toLocaleString()}
                  </span>}
                  {!temporal && error &&
                    <ClrIcon className='is-solid' style={{color: colors.white}} shape='exclamation-triangle' size={22}/>
                  }
                  {showGroupError && <span>
                    -- &nbsp;
                    <TooltipTrigger content={this.groupErrorText}>
                      <ClrIcon style={{color: colors.warning}} shape='warning-standard' size={18}/>
                    </TooltipTrigger>
                  </span>}
                </div>
              </div>
            </div>
          </div>}
        </div>
        {/* Overlay for deleted and suppressed groups */}
        {!!overlayStyle && <div style={{...styles.overlay, ...overlayStyle}} data-test-id='disabled-overlay'>
          <div style={styles.overlayInner}>
            {status === 'pending' && <React.Fragment>
              <ClrIcon className='is-solid' shape='exclamation-triangle' size={56}/>
              <span>
                This group has been deleted
                <button style={styles.overlayButton} onClick={() => this.undo()}>UNDO</button>
              </span>
            </React.Fragment>}
            {status === 'hidden' && <React.Fragment>
              <ClrIcon className='is-solid' shape='eye-hide' size={56}/>
              <span>
                This group has been suppressed
                <button style={styles.overlayButton} onClick={() => this.enable()}>ENABLE</button>
              </span>
            </React.Fragment>}
          </div>
        </div>}
        {renaming && <RenameModal existingNames={this.existingGroupNames}
          oldName={name || 'this group'}
          hideDescription={true}
          onCancel={() => this.setState({renaming: false})}
          onRename={(v) => this.rename(v)} resourceType={ResourceType.COHORTSEARCHGROUP} />}
      </React.Fragment>;
    }
  }
);

// ui/src/app/cohort-search/search-group/search-group.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {FormControl, FormGroup, Validators} from '@angular/forms';
import {DOMAIN_TYPES, PROGRAM_TYPES} from 'app/cohort-search/constant';
import {criteriaMenuOptionsStore, initExisting, searchRequestStore, wizardStore} from 'app/cohort-search/search-state.service';
import {domainToTitle, generateId, mapGroup, typeToTitle} from 'app/cohort-search/utils';
import {integerAndRangeValidator} from 'app/cohort-search/validators';
import {cohortBuilderApi} from 'app/services/swagger-fetch-clients';
import {triggerEvent} from 'app/utils/analytics';
import {currentWorkspaceStore} from 'app/utils/navigation';
import {DomainType, SearchRequest, TemporalMention, TemporalTime} from 'generated/fetch';

@Component({
  selector: 'app-list-search-group',
  templateUrl: './search-group.component.html',
  styleUrls: [
    './search-group.component.css',
    '../../styles/buttons.css',
  ]
})
export class SearchGroupComponent implements OnInit {
  @Input() group;
  @Input() index;
  @Input() role: keyof SearchRequest;
  @Input() updateRequest: Function;

  whichMention = [
    TemporalMention.ANYMENTION,
    TemporalMention.FIRSTMENTION,
    TemporalMention.LASTMENTION
  ];

  timeDropDown = [
    TemporalTime.DURINGSAMEENCOUNTERAS,
    TemporalTime.XDAYSAFTER,
    TemporalTime.XDAYSBEFORE,
    TemporalTime.WITHINXDAYSOF
  ];
  name = this.whichMention[0];
  readonly domainTypes = DOMAIN_TYPES;
  readonly programTypes = PROGRAM_TYPES;
  timeForm = new FormGroup({
    inputTimeValue: new FormControl([Validators.required],
      [integerAndRangeValidator('Form', 0, 9999)]),
  });
  demoOpen = false;
  demoMenuHover = false;
  position = 'bottom-left';
  count: number;
  error = false;
  loading = false;
  preventInputCalculate = false;
  apiCallCheck = 0;
  criteriaMenuOptions = {programTypes: [], domainTypes: []};

  ngOnInit(): void {
    this.timeForm.valueChanges
      .debounceTime(500)
      .distinctUntilChanged((p: any, n: any) => JSON.stringify(p) === JSON.stringify(n))
      .map(({inputTimeValue}) => inputTimeValue)
      .subscribe(this.getTimeValue);

    const {cdrVersionId} = currentWorkspaceStore.getValue();
    criteriaMenuOptionsStore.filter(options => !!options[cdrVersionId]).subscribe(options => {
      this.criteriaMenuOptions = options[cdrVersionId];
      setTimeout(() => this.setDemoMenuHover());
    });
  }

  setDemoMenuHover() {
    if (typeof ResizeObserver === 'function') {
      const groupDiv = document.getElementById(this.group.id);
      // check that groupDiv is of type Element
      if (groupDiv && groupDiv.tagName) {
        // create observer to reposition overlays on div resize
        const ro = new ResizeObserver(() => {
          if (this.status === 'hidden' || this.status === 'pending') {
            this.setOverlayPosition();
          }
        });
        ro.observe(groupDiv);
      }
    }
    const demoItem = document.getElementById('DEMO-' + this.index);
    if (demoItem) {
      demoItem.addEventListener('mouseenter', () => {
        this.demoOpen = true;
        setTimeout(() => {
          const demoMenu = document.getElementById('demo-menu-' + this.index);
          demoMenu.addEventListener('mouseenter', () => this.demoMenuHover = true);
          demoMenu.addEventListener('mouseleave', () => this.demoMenuHover = false);
        });
      });
      demoItem.addEventListener('mouseleave', () => setTimeout(() => this.demoOpen = false));
    }
  }

  getGroupCount() {
    try {
      this.apiCallCheck++;
      const localCheck = this.apiCallCheck;
      const {cdrVersionId} = currentWorkspaceStore.getValue();
      const group = mapGroup(this.group);
      const request = <SearchRequest>{
        includes: [],
        excludes: [],
        [this.role]: [group]
      };
      cohortBuilderApi().countParticipants(+cdrVersionId, request).then(count => {
        if (localCheck === this.apiCallCheck) {
          this.count = count;
          this.loading = false;
        }
      }, (err) => {
        console.error(err);
        this.error = true;
        this.loading = false;
      });
    } catch (error) {
      console.error(error);
      this.error = true;
      this.loading = false;
    }
  }

  update = () => {
    // timeout prevents Angular 'value changed after checked' error
    setTimeout(() => {
      // prevent multiple total count calls when initializing multiple groups simultaneously
      // (on cohort edit or clone)
      const init = initExisting.getValue();
      if (!init || (init && this.index === 0)) {
        this.updateRequest();
        if (init) {
          this.preventInputCalculate = true;
          initExisting.next(false);
        }
      }
      if (this.activeItems && (!this.temporal || !this.temporalError)) {
        this.loading = true;
        this.error = false;
        this.getGroupCount();
      }
    });
  }

  get activeItems() {
    return this.group.items.some(it => it.status === 'active');
  }

  get items() {
    return !this.group.temporal ? this.group.items
      : this.group.items.filter(it => it.temporalGroup === 0);
  }

  get temporalItems() {
    return !this.group.temporal ? [] : this.group.items.filter(it => it.temporalGroup === 1);
  }

  get disableTemporal() {
    return this.items.some(it =>
      [DomainType.PHYSICALMEASUREMENT, DomainType.PERSON, DomainType.SURVEY].includes(it.type));
  }

  get temporal() {
    return this.group.temporal;
  }

  get groupId() {
    return this.group.id;
  }

  get status() {
    return this.group.status;
  }

  remove() {
    triggerEvent('Delete', 'Click', 'Snowman - Delete Group - Cohort Builder');
    this.hide('pending');
    const timeoutId = setTimeout(() => {
      this.removeGroup();
    }, 10000);
    this.setGroupProperty('timeout', timeoutId);
  }

  hide(status: string) {
    triggerEvent('Suppress', 'Click', 'Snowman - Suppress Group - Cohort Builder');
    setTimeout(() => this.setOverlayPosition());
    this.setGroupProperty('status', status);
  }

  enable() {
    triggerEvent('Enable', 'Click', 'Enable - Suppress Group - Cohort Builder');
    this.setGroupProperty('status', 'active');
  }

  undo() {
    triggerEvent('Undo', 'Click', 'Undo - Delete Group - Cohort Builder');
    clearTimeout(this.group.timeout);
    this.enable();
  }

  removeGroup(): void {
    const searchRequest = searchRequestStore.getValue();
    searchRequest[this.role] = searchRequest[this.role].filter(grp => grp.id !== this.group.id);
    searchRequestStore.next(searchRequest);
  }

  setOverlayPosition() {
    const groupCard = document.getElementById(this.group.id);
    if (groupCard) {
      const {marginBottom, width, height} = window.getComputedStyle(groupCard);
      const overlay = document.getElementById('overlay_' + this.group.id);
      const styles = 'width:' + width + '; height:' + height + '; margin: -'
        + (parseFloat(height) + parseFloat(marginBottom)) + 'px 0 ' + marginBottom + ';';
      overlay.setAttribute('style', styles);
    }
  }

  get mention() {
    return this.group.mention;
  }

  get time() {
    return this.group.time;
  }

  get timeValue() {
    return this.group.timeValue;
  }

  launchWizard(criteria: any, tempGroup?: number) {
    const {domain, type, standard} = criteria;
    if (tempGroup !== undefined) {
      triggerEvent('Temporal', 'Click', `${domainToTitle(domain)} - Temporal - Cohort Builder`);
    } else {
      const category = `${this.role === 'includes' ? 'Add' : 'Excludes'} Criteria`;
      // If domain is PERSON, list the type as well as the domain in the label
      const label = domainToTitle(domain) +
        (domain === DomainType.PERSON ? ' - ' + typeToTitle(type) : '') +
        ' - Cohort Builder';
      triggerEvent(category, 'Click', `${category} - ${label}`);
    }
    const itemId = generateId('items');
    tempGroup = tempGroup || 0;
    const item = this.initItem(itemId, domain, tempGroup);
    const fullTree = criteria.fullTree || false;
    const role = this.role;
    const groupId = this.group.id;
    const context = {item, domain, type, standard, role, groupId, itemId, fullTree, tempGroup};
    wizardStore.next(context);
  }

  initItem(id: string, type: string, tempGroup: number) {
    return {
      id,
      type,
      searchParameters: [],
      modifiers: [],
      count: null,
      temporalGroup: tempGroup,
      status: 'active'
    };
  }

  setGroupProperty(property: string, value: any) {
    const searchRequest = searchRequestStore.getValue();
    searchRequest[this.role] = searchRequest[this.role].map(grp => {
      if (grp.id === this.group.id) {
        grp[property] = value;
      }
      return grp;
    });
    searchRequestStore.next(searchRequest);
    this.updateRequest();
  }

  getTemporal(e) {
    const {checked} = e.target;
    triggerEvent('Temporal', 'Click', 'Turn On Off - Temporal - Cohort Builder');
    this.setGroupProperty('temporal', checked);
    if ((!checked && this.activeItems) || (checked && !this.temporalError)) {
      this.loading = true;
      this.error = false;
      this.getGroupCount();
    }
  }

  getMentionTitle(mentionName) {
    if (mentionName !== this.group.mention) {
      triggerEvent(
        'Temporal',
        'Click',
        `${this.formatOption(mentionName)} - Temporal - Cohort Builder`
      );
      this.setGroupProperty('mention', mentionName);
      this.calculateTemporal();
    }
  }

  getTimeTitle(timeName) {
    if (timeName !== this.group.time) {
      triggerEvent(
        'Temporal',
        'Click',
        `${this.formatOption(timeName)} - Temporal - Cohort Builder`
      );
      // prevents duplicate group count calls if switching from TemporalTime.DURINGSAMEENCOUNTERAS
      this.preventInputCalculate = this.group.time === TemporalTime.DURINGSAMEENCOUNTERAS;
      this.setGroupProperty('time', timeName);
      this.calculateTemporal();
    }
  }

  getTimeValue = (value: number) => {
    // prevents duplicate group count calls if changes is triggered by rendering of input
    if (!this.preventInputCalculate) {
      this.setGroupProperty('timeValue', value);
      this.calculateTemporal();
    } else {
      this.preventInputCalculate = false;
    }
  }

  calculateTemporal() {
    if (!this.temporalError) {
      this.loading = true;
      this.error = false;
      this.getGroupCount();
    }
  }

  formatOption(option) {
    switch (option) {
      case TemporalMention.ANYMENTION:
        return 'Any Mention';
      case TemporalMention.FIRSTMENTION:
        return 'First Mention';
      case TemporalMention.LASTMENTION:
        return 'Last Mention';
      case TemporalTime.DURINGSAMEENCOUNTERAS:
        return 'During same encounter as';
      case TemporalTime.XDAYSBEFORE:
        return 'X Days before';
      case TemporalTime.XDAYSAFTER:
        return 'X Days after';
      case TemporalTime.WITHINXDAYSOF:
        return 'Within X Days of';
    }
  }

  get groupDisableFlag() {
    return !this.temporal && !this.group.items.length;
  }

  get temporalError() {
    const counts = this.group.items.reduce((acc, it) => {
      if (it.status === 'active') {
        acc[it.temporalGroup]++;
      }
      return acc;
    }, [0, 0]);
    const inputError = this.group.time !== TemporalTime.DURINGSAMEENCOUNTERAS &&
      (this.group.timeValue === null || this.group.timeValue < 0);
    return counts.includes(0) || inputError;
  }

  get validateInput() {
    return this.group.temporal && this.group.time !== TemporalTime.DURINGSAMEENCOUNTERAS;
  }

  setMenuPosition() {
    const id = this.role + this.index + '-button';
    const dropdown = document.getElementById(id).getBoundingClientRect();
    this.position = (window.innerHeight - dropdown.bottom < 315) ? 'top-left' : 'bottom-left';
  }
}

<div [id]="group.id" class="card bg-faded">
  <div class="card-header">
    <clr-dropdown>
      <button type="button" clrDropdownTrigger>
        <clr-icon shape="ellipsis-vertical" class="ellipsis-vertical"></clr-icon>
      </button>
      <clr-dropdown-menu *clrIfOpen>
        <button
          type="button"
          (click)="hide('hidden')"
          clrDropdownItem>
          Suppress group from total count
        </button>
        <button
          type="button"
          (click)="remove()"
          clrDropdownItem>
          Delete group
        </button>
      </clr-dropdown-menu>
    </clr-dropdown>
    Group {{index + 1}}
  </div>
  <div class="card-block" *ngIf="temporal">
    <clr-dropdown>
      <button type="button" class="btn time-selection-button" clrDropdownTrigger>
        <span>{{formatOption(mention)}}</span>
        <clr-icon shape="caret down"></clr-icon>
      </button>
      <clr-dropdown-menu clrPosition="bottom-left" *clrIfOpen>
        <button
          *ngFor="let mention of whichMention;"
          id="{{mention}}"
          class="dropdown-item"
          type="button"
          (click)="getMentionTitle(mention)"
          clrDropdownItem>{{formatOption(mention)}}</button>
      </clr-dropdown-menu>
    </clr-dropdown>
    <span class="of-text"> of </span>
  </div>

  <div *ngFor="let item of items; let i = index;" class="card-block search-item">
    <app-list-search-group-item
      [role]="role"
      [groupId]="groupId"
      [item]="item"
      [index]="i"
      [updateGroup]="update">
    </app-list-search-group-item>
    <div *ngIf="status === 'active'" class="item-or">OR</div>
  </div>

  <div class="card-block">
    <ng-template #groupDropDown>
      <clr-dropdown>
        <button [id]="role + index + '-button'" type="button" class="btn selection-button" (click)="setMenuPosition()" clrDropdownTrigger>
          Add Criteria <clr-icon shape="caret down"></clr-icon>
        </button>
        <clr-dropdown-menu clrPosition="{{position}}">
          <h4 class="dropdown-header">Program Data</h4>
          <clr-dropdown *ngFor="let criteria of programTypes">
            <button
              *ngIf="!criteria.children"
              [id]="criteria.domain"
              class="dropdown-item"
              type="button"
              (click)="launchWizard(criteria)"
              clrDropdownItem>{{criteria.name}}</button>
            <ng-container *ngIf="criteria.children">
              <button
                [id]="'DEMO-' + index"
                class="dropdown-item"
                type="button"
                clrDropdownTrigger>{{criteria.name}}</button>
              <ng-template [(clrIfOpen)]="demoOpen || demoMenuHover">
                <clr-dropdown-menu [id]="'demo-menu-' + index">
                  <button
                    *ngFor="let child of criteria.children"
                    [id]="child.type"
                    class="dropdown-item"
                    type="button"
                    (click)="launchWizard(child)"
                    clrDropdownItem>{{child.name}}</button>
              </clr-dropdown-menu>
            </ng-template>
            </ng-container>
          </clr-dropdown>
          <div class="dropdown-divider"></div>
          <h4 class="dropdown-header">Domains</h4>
          <clr-dropdown *ngFor="let criteria of domainTypes">
            <button
              *ngIf="!criteria.children"
              [id]="criteria.domain"
              class="dropdown-item"
              type="button"
              (click)="launchWizard(criteria)"
              clrDropdownItem>{{criteria.name}}</button>
            <ng-container *ngIf="criteria.children">
              <button
                [id]="criteria.domain + '-' + index"
                class="dropdown-item"
                type="button"
                clrDropdownTrigger>{{criteria.name}}</button>
              <ng-template [(clrIfOpen)]="demoOpen || demoMenuHover">
                <clr-dropdown-menu [id]="'demo-menu-' + index">
                  <button
                    *ngFor="let child of criteria.children"
                    [id]="child.subtype"
                    class="dropdown-item"
                    type="button"
                    (click)="launchWizard(child)"
                    clrDropdownItem>{{child.name}}</button>
                </clr-dropdown-menu>
              </ng-template>
            </ng-container>
          </clr-dropdown>
        </clr-dropdown-menu>
      </clr-dropdown>
    </ng-template>
    <clr-dropdown *ngIf="temporal; else groupDropDown">
      <button type="button" class="btn selection-button" clrDropdownTrigger>
        Add Criteria <clr-icon shape="caret down"></clr-icon>
      </button>
      <clr-dropdown-menu clrPosition="bottom-left" *clrIfOpen>
        <ng-container *ngFor="let criteria of domainTypes">
          <button *ngIf="criteria.name !== 'Demographics'"
            [id]="criteria.domain"
            class="dropdown-item"
            type="button"
            (click)="launchWizard(criteria)"
            clrDropdownItem>{{criteria.name}}</button>
        </ng-container>
      </clr-dropdown-menu>
    </clr-dropdown>
  </div>

  <app-validator-errors *ngIf="validateInput" [form]="timeForm"></app-validator-errors>
  <ng-container *ngIf="temporal">
    <div class="temporal-sub-card-header">
      <clr-dropdown>
        <button type="button" class="btn time-selection-button" clrDropdownTrigger>
          <span>{{formatOption(time)}}</span>
           <clr-icon shape="caret down"></clr-icon>
        </button>
        <clr-dropdown-menu clrPosition="bottom-left" *clrIfOpen>
          <button
            *ngFor="let timeName of timeDropDown"
            id="{{timeName}}"
            class="dropdown-item"
            type="button"
            (click)="getTimeTitle(timeName)"
            clrDropdownItem>{{formatOption(timeName)}}</button>
        </clr-dropdown-menu>
      </clr-dropdown>
      <form [formGroup]="timeForm" class="form-padding">
        <input *ngIf="time !== 'DURING_SAME_ENCOUNTER_AS'"  class="time-inputBox"
          type="number"
          [name]="timeValue"
          [id]="timeValue"
          [ngModel] = "timeValue"
          formControlName="inputTimeValue">
      </form>
    </div>
    <div *ngFor="let item of temporalItems" class="card-block search-item">
      <app-list-search-group-item
        class="test"
        [role]="role"
        [groupId]="groupId"
        [item]="item"
        [updateGroup]="update">
      </app-list-search-group-item>
      <div *ngIf="status === 'active'" class="item-or">OR</div>
    </div>
    <div class="temporal-sub-card-header">
      <clr-dropdown>
        <button type="button" class="btn selection-button" clrDropdownTrigger>
          Add Criteria <clr-icon shape="caret down"></clr-icon>
        </button>
        <clr-dropdown-menu clrPosition="bottom-left" *clrIfOpen>
          <ng-container *ngFor="let criteria of domainTypes">
            <button *ngIf="criteria.name !== 'Demographics'"
                    [id]="criteria.domain"
                    class="dropdown-item"
                    type="button"
                    (click)="launchWizard(criteria, 1)"
                    clrDropdownItem>{{criteria.name}}</button>
          </ng-container>
        </clr-dropdown-menu>
      </clr-dropdown>
    </div>
  </ng-container>
  <div class="container card-footer" *ngIf="activeItems || !groupDisableFlag">
    <div class="row" [class.toggle-no-cursor]="disableTemporal">
      <div class="col-sm-6 temporal-container">
        <div class="toggle-switch" [class.toggle-switch-disable]="disableTemporal">
          <input class=" ng-valid ng-dirty ng-touched" [id]="'toggle'+ index" type="checkbox"
                 [checked]="temporal" (click)="getTemporal($event)">
          <label [for]="'toggle'+ index">
            <span class="solid-preview-label"></span>
          </label>
        </div>
        <div style="padding-left: 2rem">Temporal</div>
      </div>
      <div class="col-sm-6 text-right">
        <div
          [class.error]="error"
          [popper]="errorPopper"
          [popperTrigger]="'hover'"
          [popperDisabled]="!error">
          Group Count:
          <span *ngIf="loading && (!group.temporal || !temporalError)"
            class="spinner spinner-inline group"
            [style.vertical-align]="'middle'">
          Loading...
          </span>
          <ng-container [ngSwitch]="true">
            <span *ngIf="!loading">
              <ng-container *ngSwitchCase="(!temporal || (temporal && !temporalError)) && activeItems">
                {{count | number}}
              </ng-container>
              <ng-container *ngSwitchCase="(count === null || !activeItems) && !temporal">
                 --
                <clr-tooltip>
                  <clr-icon clrTooltipTrigger shape="warning-standard" size="21"></clr-icon>
                  <clr-tooltip-content clrSize="lg" *clrIfOpen>
                    <span>
                      All criteria in this group are suppressed. Un-suppress criteria to update the group count based on the visible criteria.
                    </span>
                  </clr-tooltip-content>
                </clr-tooltip>
              </ng-container>
            </span>
            <span *ngSwitchCase="error && !temporal">
              <clr-icon
                class="is-solid"
                shape="exclamation-triangle"
                style="color: #ffffff"
                size="22"></clr-icon>
            </span>
            <span *ngSwitchCase="temporal && temporalError">
              --
              <clr-icon
                [popper]="errorPopper"
                [popperTrigger]="'hover'"
                shape="warning-standard"
                size="18"></clr-icon>
            </span>
          </ng-container>
        </div>
      </div>
    </div>
  </div>
</div>
<div
  [id]="'overlay_' + group.id"
  class="group-overlay"
  [class.pending]="status === 'pending'"
  [class.hidden]="status === 'hidden'">
  <div class="group-overlay-inner">
    <ng-container *ngIf="status ==='pending'">
      <clr-icon shape="exclamation-triangle" class="is-solid" size="56"></clr-icon>
      <span class="overlay-text">
        This group has been deleted
        <button class="btn btn-link" (click)="undo()">UNDO</button>
      </span>
    </ng-container>
    <ng-container *ngIf="status ==='hidden'">
      <clr-icon shape="eye-hide" class="is-solid" size="56"></clr-icon>
      <span class="overlay-text">
        This group has been suppressed
        <button class="btn btn-link" (click)="enable()">ENABLE</button>
      </span>
    </ng-container>
  </div>
</div>

<popper-content #errorPopper>
  <p *ngIf="error && !temporal" [style.margin]="'0'">Sorry, the request cannot be completed. Please try again or contact Support in the left hand navigation.</p>
  <p *ngIf="temporal && temporalError" [style.margin]="'0'">
    Please complete criteria selections before saving temporal relationship.
  </p>
</popper-content>
