// ui/src/app/pages/data/cohort/demographics.tsx
import * as React from 'react';
import Nouislider from 'nouislider-react';

import { AttrName, CriteriaType, Domain, Operator } from 'generated/fetch';

import { Button } from 'app/components/buttons';
import { ClrIcon } from 'app/components/icons';
import { NumberInput, RadioButton } from 'app/components/inputs';
import { Spinner } from 'app/components/spinners';
import { typeToTitle } from 'app/pages/data/cohort/utils';
import { cohortBuilderApi } from 'app/services/swagger-fetch-clients';
import colors, { colorWithWhiteness } from 'app/styles/colors';
import { reactStyles } from 'app/utils';
import { AnalyticsTracker } from 'app/utils/analytics';
import { currentWorkspaceStore } from 'app/utils/navigation';

const styles = reactStyles({
  ageContainer: {
    margin: '0.75rem 1.5rem',
    maxHeight: '22.5rem',
    padding: '0.75rem 0 2.25rem 1.5rem',
    width: '80%',
  },
  ageInput: {
    fontSize: '13px',
    marginTop: '0.375rem',
    padding: '0 0 0 0.75rem',
  },
  count: {
    alignItems: 'center',
    background: colors.accent,
    borderRadius: '10px',
    color: colors.white,
    display: 'inline-flex',
    fontSize: '10px',
    height: '0.9375rem',
    justifyContent: 'center',
    lineHeight: 'normal',
    margin: '0 0.375rem',
    minWidth: '1.0125rem',
    padding: '0 4px',
    verticalAlign: 'middle',
  },
  countPreview: {
    backgroundColor: colorWithWhiteness(colors.secondary, 0.8),
    padding: '0.75rem',
    margin: '0.75rem',
    width: '35%',
  },
  option: {
    color: colors.black,
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 400,
    marginBottom: '0.75rem',
    padding: '0 0.375rem',
    textTransform: 'capitalize',
  },
  selectIcon: {
    color: colors.select,
    marginRight: '0.375rem',
  },
  selected: {
    cursor: 'not-allowed',
    opacity: 0.4,
  },
  selectList: {
    alignItems: 'center',
    marginRight: '1.5rem',
    maxHeight: '22.5rem',
    overflow: 'auto',
    padding: '0.75rem 0 0 0.375rem',
  },
  slider: {
    flex: 1,
    padding: '0 0.75rem',
    margin: '0 1.5rem',
  },
  sliderContainer: {
    alignItems: 'center',
    display: 'flex',
    marginRight: '1.5rem',
    paddingLeft: '1.5rem',
  },
});
// Template node used for age selections
const ageNode = {
  hasAncestorData: false,
  code: '',
  domainId: Domain.PERSON,
  group: false,
  standard: true,
  type: CriteriaType.AGE,
  value: '',
};
// Forces scrollbar to be visible when the container has overlapping content
const scrollbarCSS = `
  .show-scrollbar::-webkit-scrollbar {
    -webkit-appearance: none;
    width: 7px;
  }
  .show-scrollbar::-webkit-scrollbar-thumb {
    border-radius: 4px;
    background-color: rgba(0, 0, 0, .5);
    box-shadow: 0 0 1px rgba(255, 255, 255, .5);
  }
`;

const ageTypes = [
  { label: 'Current Age', type: AttrName.AGE },
  { label: 'Age at Consent', type: AttrName.AGE_AT_CONSENT },
  { label: 'Age at CDR Date', type: AttrName.AGE_AT_CDR },
];

const defaultMinAge = '17';
const defaultMaxAge = '125';

function sortByCountThenName(critA, critB) {
  const A = critA.count || 0;
  const B = critB.count || 0;
  const diff = B - A;
  return diff === 0 ? (critA.name > critB.name ? 1 : -1) : diff;
}

interface Props {
  criteriaType: CriteriaType;
  select: Function;
  selectedIds: Array<string>;
  selections: Array<any>;
}

interface State {
  ageType: AttrName;
  ageTypeNodes: any;
  calculating: boolean;
  count: number;
  loading: boolean;
  maxAge: string;
  minAge: string;
  nodes: Array<any>;
}

interface Slider {
  get: () => Array<string>;
  set: (values: Array<number>) => void;
}

export class Demographics extends React.Component<Props, State> {
  ageWrapper: HTMLDivElement;
  slider: Slider;

  constructor(props: Props) {
    super(props);
    this.state = {
      ageType: AttrName.AGE,
      ageTypeNodes: undefined,
      calculating: false,
      count: null,
      loading: true,
      maxAge: defaultMaxAge,
      minAge: defaultMinAge,
      nodes: undefined,
    };
  }

  componentDidMount(): void {
    if (this.props.criteriaType === CriteriaType.AGE) {
      this.loadAgeNodesFromApi();
    } else {
      this.loadNodesFromApi();
    }
  }

  componentDidUpdate(prevProps: Readonly<Props>): void {
    const { criteriaType, selections } = this.props;
    if (
      selections !== prevProps.selections &&
      criteriaType !== CriteriaType.AGE
    ) {
      this.calculate();
    }
  }

  async loadNodesFromApi() {
    const { criteriaType, selections } = this.props;
    const { id, namespace } = currentWorkspaceStore.getValue();
    this.setState({ loading: true });
    const response = await cohortBuilderApi().findCriteriaBy(
      namespace,
      id,
      Domain.PERSON.toString(),
      criteriaType.toString()
    );
    const nodes = response.items
      .filter((item) => item.count !== -1)
      .sort(sortByCountThenName)
      .map((node) => ({
        ...node,
        parameterId: `param${node.conceptId || node.code}`,
      }));
    if (selections.length) {
      this.calculate(true);
    }
    this.setState({ loading: false, nodes });
  }

  async loadAgeNodesFromApi() {
    const { id, namespace } = currentWorkspaceStore.getValue();
    const initialValue = {
      [AttrName.AGE]: [],
      [AttrName.AGE_AT_CONSENT]: [],
      [AttrName.AGE_AT_CDR]: [],
    };
    const response = await cohortBuilderApi().findAgeTypeCounts(namespace, id);
    const ageTypeNodes = response.items.reduce((acc, item) => {
      acc[item.ageType].push(item);
      return acc;
    }, initialValue);
    this.setState({ ageTypeNodes }, () => this.calculateAgeFromNodes());
  }

  onMinChange(minAge: string) {
    const { maxAge } = this.state;
    let sliderMin = +minAge;
    if (+minAge < +defaultMinAge) {
      sliderMin = +defaultMinAge;
    } else if (+minAge > +maxAge) {
      sliderMin = +maxAge;
    }
    this.slider.set([sliderMin, null]);
    this.setState({ minAge }, () => this.calculateAgeFromNodes('min'));
  }

  onMaxChange(maxAge: string) {
    const { minAge } = this.state;
    let sliderMax = +maxAge;
    if (+maxAge > +defaultMaxAge) {
      sliderMax = +defaultMaxAge;
    } else if (+maxAge < +minAge) {
      sliderMax = +minAge;
    }
    this.slider.set([null, sliderMax]);
    this.setState({ maxAge }, () => this.calculateAgeFromNodes('max'));
  }

  onMaxBlur() {
    const { minAge } = this.state;
    let { maxAge } = this.state;
    if (+maxAge < +minAge) {
      maxAge = minAge;
    } else if (+maxAge > +defaultMaxAge || maxAge === '') {
      maxAge = defaultMaxAge;
    }
    this.slider.set([null, +maxAge]);
    this.setState({ maxAge });
  }

  onMinBlur() {
    const { maxAge } = this.state;
    let { minAge } = this.state;
    if (+minAge > +maxAge) {
      minAge = maxAge;
    } else if (+minAge < +defaultMinAge || minAge === '') {
      minAge = defaultMinAge;
    }
    this.slider.set([+minAge, null]);
    this.setState({ minAge });
  }

  onRadioChange(ageType: AttrName) {
    this.setState({ ageType }, () => this.calculateAgeFromNodes());
  }

  onSliderInit(slider) {
    this.slider = slider.noUiSlider;
    if (this.slider) {
      this.centerAgeCount();
    }
  }

  onSliderUpdate(range: Array<string>) {
    // Use split here to drop the decimals (the slider defaults to 2 decimal places)
    const [min, max] = range.map((n) => n.split('.')[0]);
    this.setState({ maxAge: max, minAge: min }, () =>
      this.calculateAgeFromNodes()
    );
  }

  get ageParameterId() {
    const { ageType, maxAge, minAge } = this.state;
    return `${ageType.toString()}-${minAge}-${maxAge}`;
  }

  addAgeSelection() {
    const { ageType, maxAge, minAge } = this.state;
    const ageTypeLabel = ageTypes.find((at) => at.type === ageType).label;
    const selectedNode = {
      ...ageNode,
      parameterId: this.ageParameterId,
      name: `${ageTypeLabel} In Range ${minAge} - ${maxAge}`,
      attributes: [
        {
          name: ageType.toString(),
          operator: Operator.BETWEEN,
          operands: [minAge, maxAge],
        },
      ],
    };
    this.props.select(selectedNode);
  }

  centerAgeCount() {
    if (!!this.slider) {
      // get range from slider element and convert the strings to numbers
      const [sliderMin, sliderMax] = this.slider.get().map((v) => +v);
      // get width as a % by dividing the selected age range by the full slider range
      const width =
        ((sliderMax - sliderMin) / (+defaultMaxAge - +defaultMinAge)) * 100;
      // get left margin as a % by dividing the change in minAge by the full slider range
      const marginLeft =
        ((sliderMin - +defaultMinAge) / (+defaultMaxAge - +defaultMinAge)) *
        100;
      const wrapper = document.getElementById('count-wrapper');
      if (!!wrapper) {
        wrapper.setAttribute(
          'style',
          `margin-left: ${marginLeft}%; width: ${width}%; text-align: center;`
        );
        // set style properties also for cross-browser compatibility
        wrapper.style.marginLeft = `${marginLeft}%`;
        wrapper.style.width = `${width}%`;
        wrapper.style.textAlign = 'center';
      }
    }
  }

  selectOption(opt: any) {
    AnalyticsTracker.CohortBuilder.SelectDemographics(
      `Select ${typeToTitle(opt.type)} - ${opt.name}`
    );
    this.props.select({
      ...opt,
      name: `${typeToTitle(opt.type)} - ${opt.name}`,
    });
  }

  calculate(init?: boolean) {
    let count = 0;
    this.props.selections.forEach((sp) => {
      if (init) {
        const node = this.state.nodes.find((n) => n.conceptId === sp.conceptId);
        if (node) {
          sp.count = node.count;
        }
      }
      count += sp.count;
    });
    this.setState({ count });
  }

  calculateAgeFromNodes(minOrMax?: string) {
    const { ageTypeNodes, ageType, maxAge, minAge } = this.state;
    let max = +maxAge;
    let min = +minAge;
    if (minOrMax === 'min' && min > +max) {
      min = max;
    } else if (minOrMax === 'max' && max < min) {
      max = min;
    }
    const count = ageTypeNodes[ageType]
      .filter((node) => node.age >= min && node.age <= max)
      .reduce((acc, node) => acc + node.count, 0);
    this.setState({ count, loading: false }, () => this.centerAgeCount());
  }

  get showPreview() {
    const { selections } = this.props;
    return !this.state.loading && !!selections && selections.length > 0;
  }

  render() {
    const { criteriaType, selectedIds } = this.props;
    const { ageType, calculating, count, loading, maxAge, minAge, nodes } =
      this.state;
    return loading ? (
      <div style={{ textAlign: 'center' }}>
        <Spinner style={{ marginTop: '4.5rem' }} />
      </div>
    ) : criteriaType === CriteriaType.AGE ? (
      // Age slider with number inputs
      <div style={styles.ageContainer}>
        <div style={styles.sliderContainer}>
          <div style={{ width: '3.75rem' }}>
            <NumberInput
              style={styles.ageInput}
              min={defaultMinAge}
              max={maxAge}
              value={minAge}
              onBlur={() => this.onMinBlur()}
              onChange={(v) => this.onMinChange(v)}
            />
          </div>
          <div style={{ ...styles.slider, marginBottom: '1.125rem' }}>
            <div ref={(el) => (this.ageWrapper = el)} id='count-wrapper'>
              {calculating ? (
                <Spinner size={16} />
              ) : (
                <span style={styles.count} id='age-count'>
                  {count.toLocaleString()}
                </span>
              )}
            </div>
            <Nouislider
              behaviour='drag'
              connect
              instanceRef={(slider) => this.onSliderInit(slider)}
              onSlide={(v) => this.onSliderUpdate(v)}
              range={{ min: +defaultMinAge, max: +defaultMaxAge }}
              start={[+defaultMinAge, +defaultMaxAge]}
              step={1}
            />
          </div>
          <div style={{ width: '3.75rem' }}>
            <NumberInput
              style={styles.ageInput}
              min={minAge}
              max={defaultMaxAge}
              value={maxAge}
              onBlur={() => this.onMaxBlur()}
              onChange={(v) => this.onMaxChange(v)}
            />
          </div>
          <Button
            style={{ marginLeft: '1.5rem' }}
            type='primary'
            disabled={selectedIds.includes(this.ageParameterId)}
            onClick={() => this.addAgeSelection()}
          >
            Add Selection
          </Button>
        </div>
        <div style={{ marginLeft: '1.5rem' }}>
          {ageTypes.map((ageTypeRadio, index) => (
            <div
              key={index}
              style={{ display: 'inline-block', marginRight: '0.75rem' }}
            >
              <RadioButton
                name='ageType'
                style={{ marginRight: '0.375rem' }}
                onChange={() => this.onRadioChange(ageTypeRadio.type)}
                checked={ageTypeRadio.type === ageType}
              />
              <label>{ageTypeRadio.label}</label>
            </div>
          ))}
        </div>
      </div>
    ) : (
      // List of selectable criteria used for Race, Ethnicity, Gender and Sex
      <React.Fragment>
        <style>{scrollbarCSS}</style>
        <div className='show-scrollbar' style={styles.selectList}>
          <div
            style={{ margin: '0.375rem 0', overflow: 'auto', width: '100%' }}
          >
            {nodes.map((opt, o) => (
              <div key={o} style={styles.option}>
                {selectedIds.includes(opt.parameterId) ? (
                  <ClrIcon
                    shape='check-circle'
                    size='20'
                    style={{ ...styles.selectIcon, ...styles.selected }}
                  />
                ) : (
                  <ClrIcon
                    shape='plus-circle'
                    size='20'
                    style={styles.selectIcon}
                    onClick={() => this.selectOption(opt)}
                  />
                )}
                {opt.name}
                {!!opt.count && (
                  <span style={styles.count}>{opt.count.toLocaleString()}</span>
                )}
              </div>
            ))}
          </div>
        </div>
        {this.showPreview && (
          <div style={styles.countPreview}>
            {count !== null && (
              <div style={{ fontSize: '14px' }}>
                <div style={{ color: colors.primary, fontWeight: 500 }}>
                  Results
                </div>
                <div>
                  Number Participants:
                  <b style={{ color: colors.dark }}>
                    &nbsp;{count.toLocaleString()}
                  </b>
                </div>
              </div>
            )}
          </div>
        )}
      </React.Fragment>
    );
  }
}

// ui/src/app/cohort-search/demographics/demographics.component.tsx
import {Component, Input} from '@angular/core';
import Nouislider from 'nouislider-react';
import * as React from 'react';

import {ageCountStore} from 'app/cohort-search/search-state.service';
import {mapParameter, typeToTitle} from 'app/cohort-search/utils';
import {ClrIcon} from 'app/components/icons';
import {Spinner} from 'app/components/spinners';
import {cohortBuilderApi} from 'app/services/swagger-fetch-clients';
import colors, {colorWithWhiteness} from 'app/styles/colors';
import {reactStyles, ReactWrapperBase} from 'app/utils';
import {triggerEvent} from 'app/utils/analytics';
import {currentWorkspaceStore, serverConfigStore} from 'app/utils/navigation';
import {AttrName, CriteriaType, DomainType, Operator} from 'generated/fetch';

const styles = reactStyles({
  ageContainer: {
    border: '1px solid #cccccc',
    borderRadius: '5px',
    margin: '0.5rem 1rem',
    maxHeight: '15rem',
    padding: '0.5rem 0 1.5rem 1rem'
  },
  ageInput: {
    border: `1px solid ${colors.black}`,
    borderRadius: '3px',
    fontSize: '0.5rem',
    fontWeight: 300,
    marginTop: '0.25rem',
    padding: '0 0.5rem',
    width: '1rem',
  },
  ageLabel: {
    fontSize: '14px',
    fontWeight: 600,
    color: colors.primary
  },
  calculateBtn: {
    background: colors.primary,
    border: 'none',
    borderRadius: '0.3rem',
    color: colors.white,
    cursor: 'pointer',
    fontSize: '12px',
    height: '1.5rem',
    letterSpacing: '0.02rem',
    lineHeight: '0.75rem',
    margin: '0.25rem 0.5rem 0.25rem 0',
    padding: '0rem 0.75rem',
    textTransform: 'uppercase',
  },
  count: {
    alignItems: 'center',
    background: colors.accent,
    borderRadius: '10px',
    color: colors.white,
    display: 'inline-flex',
    fontSize: '10px',
    height: '0.625rem',
    justifyContent: 'center',
    lineHeight: 'normal',
    margin: '0 0.25rem',
    minWidth: '0.675rem',
    padding: '0 4px',
    verticalAlign: 'middle'
  },
  countPreview: {
    backgroundColor: colorWithWhiteness(colors.secondary, 0.8),
    padding: '0.5rem',
    margin: '0 2.5%',
    position: 'absolute',
    width: '95%',
    bottom: '0.5rem',
  },
  option: {
    color: colors.black,
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 400,
    marginBottom: '0.5rem',
    padding: '0 0.25rem',
    textTransform: 'capitalize',
  },
  resultText: {
    color: colors.primary,
    fontWeight: 500,
  },
  selectIcon: {
    color: colors.select,
    marginRight: '0.25rem'
  },
  selected: {
    cursor: 'not-allowed',
    opacity: 0.4
  },
  selectList: {
    alignItems: 'center',
    display: 'flex',
    marginRight: '1rem',
    maxHeight: '15rem',
    padding: '0.5rem 0 0 1rem'
  },
  slider: {
    flex: 1,
    padding: '0 0.5rem',
    margin: '0 1rem',
  },
  sliderContainer: {
    alignItems: 'center',
    display: 'flex',
    marginRight: '1rem',
    paddingLeft: '1rem',
    width: '96%',
  }
});

const ageNode = {
  hasAncestorData: false,
  attributes: [],
  code: '',
  domainId: DomainType.PERSON,
  group: false,
  name: 'Age',
  parameterId: 'age-param',
  isStandard: true,
  type: CriteriaType.AGE,
  value: ''
};

const defaultMinAge = '18';
const defaultMaxAge = '120';
const enableCBAgeTypeOptions = serverConfigStore.getValue().enableCBAgeTypeOptions;

/*
 * Sorts a plain JS array of plain JS objects first by a 'count' key and then
 * by a 'name' key
 */
function sortByCountThenName(critA, critB) {
  const A = critA.count || 0;
  const B = critB.count || 0;
  const diff = B - A;
  return diff === 0
        ? (critA.name > critB.name ? 1 : -1)
        : diff;
}
interface Props {
  select: Function;
  selectedIds: Array<string>;
  selections: Array<any>;
  wizard: any;
}

interface State {
  ageType: any;
  ageTypeNodes: any;
  calculating: boolean;
  count: number;
  loading: boolean;
  maxAge: string;
  minAge: string;
  nodes: Array<any>;
}

export class Demographics extends React.Component<Props, State> {
  ageWrapper: HTMLDivElement;
  slider: any;
  ageTypes = [
    {label: 'Current Age', type: AttrName.AGE.toString()},
    {label: 'Age at Consent', type: AttrName.AGEATCONSENT.toString()},
    {label: 'Age at CDR Date', type: AttrName.AGEATCDR.toString()}
  ];

  constructor(props: Props) {
    super(props);
    this.state = {
      ageType: AttrName.AGE.toString(),
      ageTypeNodes: undefined,
      calculating: false,
      count: null,
      loading: true,
      maxAge: defaultMaxAge,
      minAge: defaultMinAge,
      nodes: undefined,
    };
  }

  componentDidMount(): void {
    if (this.props.wizard.type === CriteriaType.AGE) {
      if (enableCBAgeTypeOptions) {
        this.loadAgeNodesFromApi();
      } else {
        this.initAgeRange();
        this.setState({loading: false});
      }
    } else {
      this.loadNodesFromApi();
    }
  }

  componentDidUpdate(prevProps: Readonly<Props>): void {
    const {selections, wizard} = this.props;
    if (selections !== prevProps.selections && wizard.type !== CriteriaType.AGE) {
      this.calculate();
    }
  }

  loadNodesFromApi() {
    const {selections, wizard} = this.props;
    const {cdrVersionId} = currentWorkspaceStore.getValue();
    this.setState({loading: true});
    cohortBuilderApi().findCriteriaBy(+cdrVersionId, DomainType.PERSON.toString(), wizard.type).then(response => {
      const nodes = response.items
        .filter(item => item.parentId !== 0)
        .sort(sortByCountThenName)
        .map(node => ({...node, parameterId: `param${node.conceptId || node.code}`}));
      if (selections.length) {
        this.calculate(true);
      }
      this.setState({loading: false, nodes});
    });
  }

  loadAgeNodesFromApi() {
    const {cdrVersionId} = currentWorkspaceStore.getValue();
    const initialValue = {[AttrName.AGE.toString()]: [], 'AGE_AT_CONSENT': [], 'AGE_AT_CDR': []};
    cohortBuilderApi().findAgeTypeCounts(+cdrVersionId).then(response => {
      const ageTypeNodes = response.items.reduce((acc, item) => {
        acc[item.ageType].push(item);
        return acc;
      }, initialValue);
      this.setState({ageTypeNodes}, () => this.calculateAgeFromNodes());
    });
  }

  initAgeRange() {
    const {selections, wizard} = this.props;
    if (selections.length) {
      const {attributes} = selections[0];
      const {name, operands} = attributes[0];
      this.slider.set([+operands[0], +operands[1]]);
      this.setState({count: wizard.count, maxAge: operands[1], minAge: operands[0]});
      if (enableCBAgeTypeOptions) {
        this.setState({ageType: name});
      }
    } else {
      // timeout prevents Angular 'ExpressionChangedAfterItHasBeenCheckedError' in CB modal component
      setTimeout(() => this.updateAgeSelection());
    }
    if (!enableCBAgeTypeOptions) {
      const {cdrVersionId} = currentWorkspaceStore.getValue();
      if (!ageCountStore.getValue()[cdrVersionId]) {
        // Get total age count for this cdr version if it doesn't exist in the store yet
        this.calculateAge(true);
      } else if (this.setTotalAge) {
        this.setState({count:  ageCountStore.getValue()[cdrVersionId]});
      }
    }
  }

  onMinChange(minAge: string) {
    const {maxAge} = this.state;
    let sliderMin = +minAge;
    if (+minAge < +defaultMinAge) {
      sliderMin = +defaultMinAge;
    } else if (+minAge > +maxAge) {
      sliderMin = +maxAge;
    }
    this.slider.set([sliderMin, null]);
    this.setState({minAge}, () => {
      if (enableCBAgeTypeOptions) {
        this.calculateAgeFromNodes('min');
      }
    });
  }

  onMaxChange(maxAge: string) {
    const {minAge} = this.state;
    let sliderMax = +maxAge;
    if (+maxAge > +defaultMaxAge) {
      sliderMax = +defaultMaxAge;
    } else if (+maxAge < +minAge) {
      sliderMax = +minAge;
    }
    this.slider.set([null, sliderMax]);
    this.setState({maxAge}, () => {
      if (enableCBAgeTypeOptions) {
        this.calculateAgeFromNodes('max');
      }
    });
  }

  onMaxBlur() {
    const {minAge} = this.state;
    let {maxAge} = this.state;
    if (+maxAge < +minAge) {
      maxAge = minAge;
    } else if (+maxAge > +defaultMaxAge || maxAge === '') {
      maxAge = defaultMaxAge;
    }
    this.slider.set([null, +maxAge]);
    this.setState({maxAge}, () => this.updateAgeSelection());
  }

  onMinBlur() {
    const {maxAge} = this.state;
    let {minAge} = this.state;
    if (+minAge > +maxAge) {
      minAge = maxAge;
    } else if (+minAge < +defaultMinAge || minAge === '') {
      minAge = defaultMinAge;
    }
    this.slider.set([+minAge, null]);
    this.setState({minAge}, () => this.updateAgeSelection());
  }

  onRadioChange(ageType: string) {
    this.setState({ageType}, () => {
      this.updateAgeSelection();
      this.calculateAgeFromNodes();
    });
  }

  onSliderInit(slider: any) {
    this.slider = slider['noUiSlider'];
    if (this.slider) {
      this.initAgeRange();
      this.centerAgeCount();
    }
  }

  onSliderUpdate(range: Array<string>) {
    const [min, max] = range.map(n => n.split('.')[0]);
    // this.slider.set([+min, +max]);
    this.setState({maxAge: max, minAge: min}, () => {
      if (enableCBAgeTypeOptions) {
        this.calculateAgeFromNodes();
      }
    });
  }

  updateAgeSelection() {
    const {ageType, maxAge, minAge} = this.state;
    const selectedNode = {
      ...ageNode,
      name: `Age In Range ${minAge} - ${maxAge}`,
      attributes: [{
        name: ageType,
        operator: Operator.BETWEEN,
        operands: [minAge, maxAge]
      }],
    };
    this.props.select(selectedNode);
  }

  centerAgeCount() {
    if (enableCBAgeTypeOptions && !!this.slider) {
      // get range from slider element and convert the strings to numbers
      const [sliderMin, sliderMax] = this.slider.get().map(v => +v);
      // get width as a % by dividing the selected age range by the full slider range
      const width = (sliderMax - sliderMin) / (+defaultMaxAge - +defaultMinAge) * 100;
      // get left margin as a % by dividing the change in minAge by the full slider range
      const marginLeft = (sliderMin - +defaultMinAge) / (+defaultMaxAge - +defaultMinAge) * 100;
      const wrapper = document.getElementById('count-wrapper');
      if (!!wrapper) {
        wrapper.setAttribute('style', `margin-left: ${marginLeft}%; width: ${width}%; text-align: center;`);
        // set style properties also for cross-browser compatibility
        wrapper.style.marginLeft = `${marginLeft}%`;
        wrapper.style.width = `${width}%`;
        wrapper.style.textAlign = 'center';
      }
    }
  }

  selectOption(opt: any) {
    triggerEvent('Cohort Builder Search', 'Click', `Demo - ${typeToTitle(opt.type)} - ${opt.name}`);
    this.props.select({...opt, name: `${typeToTitle(opt.type)} - ${opt.name}`});
  }

  calculate(init?: boolean) {
    let count = 0;
    this.props.selections.forEach(sp => {
      if (init) {
        const node = this.state.nodes.find(n => n.conceptId === sp.conceptId);
        if (node) {
          sp.count = node.count;
        }
      }
      count += sp.count;
    });
    this.setState({count});
  }

  calculateAge(init?: boolean) {
    const {maxAge, minAge} = this.state;
    if (!init || this.setTotalAge) {
      this.setState({calculating: true});
    }
    const {cdrVersionId} = currentWorkspaceStore.getValue();
    const min = init ? defaultMinAge : minAge;
    const max = init ? defaultMaxAge : maxAge;
    const parameter = {
      ...ageNode,
      name: `Age In Range ${min} - ${max}`,
      attributes: [{
        name: AttrName.AGE,
        operator: Operator.BETWEEN,
        operands: [min, max]
      }],
    };
    const request = {
      excludes: [],
      includes: [{
        items: [{
          type: DomainType.PERSON.toString(),
          searchParameters: [mapParameter(parameter)],
          modifiers: []
        }],
        temporal: false
      }],
      dataFilters: []
    };
    cohortBuilderApi().countParticipants(+cdrVersionId, request).then(response => {
      if (init) {
        const ageCounts = ageCountStore.getValue();
        ageCounts[cdrVersionId] = response;
        ageCountStore.next(ageCounts);
        if (this.setTotalAge) {
          this.setState({count: response});
        }
      } else {
        this.setState({count: response});
      }
      this.setState({calculating: false});
    }, (err) => {
      console.error(err);
      this.setState({calculating: false});
    });
  }

  calculateAgeFromNodes(minOrMax?: string) {
    const {ageTypeNodes, ageType, maxAge, minAge} = this.state;
    let max = +maxAge;
    let min = +minAge;
    if (minOrMax === 'min' && min > +max) {
      min = max;
    } else if (minOrMax === 'max' && max < min) {
      max = min;
    }
    const count = ageTypeNodes[ageType]
      .filter(node => node.age >= min && node.age <= max)
      .reduce((acc, node) => acc + node.count, 0);
    this.setState({count, loading: false}, () => this.centerAgeCount());
  }

  get showPreview() {
    const {selections, wizard} = this.props;
    return !this.state.loading
      && (selections && selections.length > 0)
      && !(wizard.type === CriteriaType.AGE && enableCBAgeTypeOptions);
  }

  // Checks if form is in its initial state and if a count already exists before setting the total age count
  get setTotalAge() {
    const {count, maxAge, minAge} = this.state;
    return minAge === defaultMinAge && maxAge === defaultMaxAge && !count;
  }

  render() {
    const {selectedIds, wizard} = this.props;
    const {ageType, calculating, count, loading, maxAge, minAge, nodes} = this.state;
    const isAge = wizard.type === CriteriaType.AGE;
    return loading
      ? <div style={{textAlign: 'center'}}><Spinner style={{marginTop: '3rem'}}/></div>
      : <React.Fragment>
        {isAge
          ? <div style={styles.ageContainer}>
            <div style={styles.ageLabel}>
              Age Range
            </div>
            <div style={styles.sliderContainer}>
              <input style={styles.ageInput}
                type='number'
                id='min-age'
                min={defaultMinAge} max={maxAge}
                value={minAge}
                onBlur={() => this.onMinBlur()}
                onChange={(e) => this.onMinChange(e.target.value)}/>
              <div style={enableCBAgeTypeOptions ? {...styles.slider, marginBottom: '0.75rem'} : styles.slider}>
                {enableCBAgeTypeOptions && <div ref={(el) => this.ageWrapper = el} id='count-wrapper'>
                  {calculating
                    ? <Spinner size={16}/>
                    : <span style={styles.count} id='age-count'>
                      {count.toLocaleString()}
                    </span>
                  }
                </div>}
                <Nouislider behaviour='drag'
                  connect
                  instanceRef={(slider) => this.onSliderInit(slider)}
                  onChange={() => this.updateAgeSelection()}
                  onSlide={(v) => this.onSliderUpdate(v)}
                  range={{min: +defaultMinAge, max: +defaultMaxAge}}
                  start={[+defaultMinAge, +defaultMaxAge]}
                  step={1}/>
              </div>
              <input style={styles.ageInput}
                type='number'
                id='max-age'
                min={minAge} max={defaultMaxAge}
                value={maxAge}
                onBlur={() => this.onMaxBlur()}
                onChange={(e) => this.onMaxChange(e.target.value)}/>
            </div>
            {enableCBAgeTypeOptions && <div style={{marginLeft: '1rem'}}>
              {this.ageTypes.map((ageTypeRadio, a) => <div key={a} style={{display: 'inline-block', marginRight: '0.5rem'}}>
                <input type='radio' name='ageType'
                  style={{marginRight: '0.25rem'}}
                  onChange={() => this.onRadioChange(ageTypeRadio.type)}
                  checked={ageTypeRadio.type === ageType}/>
                <label>{ageTypeRadio.label}</label>
              </div>)}
            </div>}
          </div>
          : <div style={styles.selectList}>
            <div style={{margin: '0.25rem 0', overflow: 'auto', width: '100%'}}>
              {nodes.map((opt, o) => <div key={o} style={styles.option} onClick={() => this.selectOption(opt)}>
                {selectedIds.includes(opt.parameterId)
                  ? <ClrIcon shape='check-circle' size='20' style={{...styles.selectIcon, ...styles.selected}}/>
                  : <ClrIcon shape='plus-circle'  size='20' style={styles.selectIcon}/>
                }
                {opt.name}
                {!!opt.count && <span style={styles.count}>
                  {opt.count.toLocaleString()}
                </span>}
              </div>)}
            </div>
          </div>
        }
        {this.showPreview && <div style={isAge
          ? {...styles.countPreview, minWidth: '50%', padding: '0.25rem 1rem', width: 'auto'}
          : styles.countPreview}>
          {isAge && <div style={{float: 'left', marginRight: '0.25rem'}}>
            <button style={styles.calculateBtn} disabled={calculating || count !== null} onClick={() => this.calculateAge()}>
              {calculating && <Spinner size={16}/>}
              Calculate
            </button>
          </div>}
          {(count !== null || isAge) && <div style={{float: 'left', fontSize: '14px'}}>
            <div style={{color: colors.primary, fontWeight: 500}}>
              Results
            </div>
            <div>
              Number Participants:
              <b style={{color: colors.dark}}>
                &nbsp;{count !== null ? count.toLocaleString() : ' -- '}
              </b>
            </div>
          </div>}
        </div>}
      </React.Fragment>;
  }
}

@Component({
  selector: 'crit-demographics',
  template: '<div #root></div>'
})
export class DemographicsComponent extends ReactWrapperBase {
  @Input('select') select: Props['select'];
  @Input('selectedIds') selectedIds: Props['selectedIds'];
  @Input('selections') selections: Props['selections'];
  @Input('wizard') wizard: Props['wizard'];

  constructor() {
    super(Demographics, ['select', 'selectedIds', 'selections', 'wizard']);
  }
}
