// ui/src/app/pages/homepage/homepage.tsx
import * as React from 'react';
import { RouteComponentProps, withRouter } from 'react-router-dom';
import * as fp from 'lodash/fp';
import { faPlus } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { Profile, WorkspaceResponseListResponse } from 'generated/fetch';

import {
  Button,
  StyledExternalLink,
  StyledRouterLink,
} from 'app/components/buttons';
import { FlexColumn, FlexRow } from 'app/components/flex';
import { Header, SemiBoldHeader, SmallHeader } from 'app/components/headers';
import { ClrIcon } from 'app/components/icons';
import { CustomBulletList, CustomBulletListItem } from 'app/components/lists';
import { MigrationModal } from 'app/components/migration/migration-modal';
import { AoU } from 'app/components/text-wrappers';
import { WithSpinnerOverlayProps } from 'app/components/with-spinner-overlay';
import { RecentResources } from 'app/pages/homepage/recent-resources';
import { RecentWorkspaces } from 'app/pages/homepage/recent-workspaces';
import { VwbCreateWorkspaceModal } from 'app/pages/workspace/vwb-create-workspace-modal';
import { profileApi, workspacesApi } from 'app/services/swagger-fetch-clients';
import colors, { addOpacity } from 'app/styles/colors';
import { reactStyles, withUserProfile } from 'app/utils';
import { AnalyticsTracker } from 'app/utils/analytics';
import { fetchWithSystemErrorHandler } from 'app/utils/errors';
import { NavigationProps, useNavigation } from 'app/utils/navigation';
import { serverConfigStore } from 'app/utils/stores';
import { withNavigation } from 'app/utils/with-navigation-hoc';
import { supportUrls } from 'app/utils/zendesk';
import analysisIcon from 'assets/images/analysis-icon.svg';
import cohortIcon from 'assets/images/cohort-icon.svg';
import workspaceIcon from 'assets/images/workspace-icon.svg';

import { QuickTourAndVideos } from './quick-tour-and-videos';
import { VwbBanner } from './vwb-banner';
import { VwbMigrationBanner } from './vwb-migration-banner';

export const styles = reactStyles({
  fadeBox: {
    margin: '1.5rem 0 0 3%',
    width: '95%',
    padding: '0 0.15rem',
  },
  pageWrapper: {
    marginLeft: '-1.5rem',
    marginRight: '-0.9rem',
    justifyContent: 'space-between',
    fontSize: '1.2em',
  },
  welcomeMessageIcon: {
    height: '3.375rem',
    width: '4.125rem',
  },
});

const WelcomeHeader = () => {
  return (
    <FlexColumn style={{ marginLeft: '3%', width: '50%' }}>
      <FlexRow>
        <FlexColumn>
          <Header
            style={{
              fontWeight: 500,
              color: colors.secondary,
              fontSize: '1.38rem',
            }}
          >
            Welcome to the
          </Header>
          <Header style={{ textTransform: 'uppercase', marginTop: '0.3rem' }}>
            Researcher Workbench
          </Header>
        </FlexColumn>
        <FlexRow style={{ alignItems: 'flex-end', marginLeft: '1.5rem' }}>
          <img style={styles.welcomeMessageIcon} src={workspaceIcon} />
          <img style={styles.welcomeMessageIcon} src={cohortIcon} />
          <img style={styles.welcomeMessageIcon} src={analysisIcon} />
        </FlexRow>
      </FlexRow>
      <SmallHeader style={{ color: colors.primary, marginTop: '0.375rem' }}>
        The secure platform to analyze <AoU /> data
      </SmallHeader>
    </FlexColumn>
  );
};

const Workspaces = ({
  onChange,
  disableCreation,
}: {
  onChange: () => void;
  disableCreation: boolean;
}) => {
  const [navigate] = useNavigation();

  return (
    <FlexColumn>
      <FlexRow
        style={{ justifyContent: 'space-between', alignItems: 'center' }}
      >
        <FlexRow style={{ alignItems: 'center' }}>
          {serverConfigStore.get().config.enableVWBHomepageBanner ? (
            <>
              <SemiBoldHeader style={{ fontSize: '28px', marginTop: '0px' }}>
                Legacy Workspaces
              </SemiBoldHeader>
              <Button
                aria-label='Create Legacy Workspace'
                style={{
                  background: colors.accent,
                  borderRadius: '2rem',
                  height: '2.5rem',
                  marginLeft: '1.5rem',
                  padding: '0 1rem',
                  opacity: disableCreation ? 0.4 : 1,
                }}
                disabled={disableCreation}
                onClick={() => {
                  AnalyticsTracker.Workspaces.OpenCreatePage();
                  navigate(['workspaces', 'build']);
                }}
              >
                <FontAwesomeIcon
                  icon={faPlus}
                  style={{ marginRight: '0.5rem' }}
                  size='lg'
                />
                Create Legacy Workspace
              </Button>
            </>
          ) : (
            <>
              <SemiBoldHeader style={{ marginTop: '0px' }}>
                Workspaces
              </SemiBoldHeader>
              <ClrIcon
                aria-label='Create Workspace'
                shape='plus-circle'
                size={30}
                className={'is-solid'}
                style={{
                  color: colors.accent,
                  marginLeft: '1.5rem',
                  cursor: 'pointer',
                }}
                onClick={() => {
                  AnalyticsTracker.Workspaces.OpenCreatePage();
                  navigate(['workspaces', 'build']);
                }}
              />
            </>
          )}
        </FlexRow>
        <span
          style={{
            alignSelf: 'flex-end',
            color: colors.accent,
            cursor: 'pointer',
          }}
          onClick={() => navigate(['workspaces'])}
        >
          See all workspaces
        </span>
      </FlexRow>
      <RecentWorkspaces {...{ onChange }} />
    </FlexColumn>
  );
};

const GettingStarted = () => {
  return (
    <div
      data-test-id='getting-started'
      style={{
        backgroundColor: addOpacity(colors.primary, 0.1).toString(),
        color: colors.primary,
        borderRadius: 10,
        margin: '2em 0em',
      }}
    >
      <div style={{ margin: '1em 2em' }}>
        <h2 style={{ fontWeight: 600, marginTop: 0 }}>
          Here are some tips to get you started:
        </h2>
        <CustomBulletList>
          <CustomBulletListItem bullet='→'>
            Create a{' '}
            <StyledExternalLink
              href='https://support.google.com/chrome/answer/2364824'
              target='_blank'
            >
              Chrome Profile
            </StyledExternalLink>{' '}
            with your <AoU /> Researcher Workbench Google account. This will
            keep your workbench browser sessions isolated from your other Google
            accounts.
          </CustomBulletListItem>
          <CustomBulletListItem bullet='→'>
            Check out{' '}
            <StyledRouterLink path='/library'>
              Featured Workspaces
            </StyledRouterLink>{' '}
            from the left hand panel to browse through example workspaces.
          </CustomBulletListItem>
          <CustomBulletListItem bullet='→'>
            Browse through our{' '}
            <StyledExternalLink href={supportUrls.helpCenter} target='_blank'>
              support materials
            </StyledExternalLink>{' '}
            and forum topics.
          </CustomBulletListItem>
        </CustomBulletList>
      </div>
    </div>
  );
};

interface Props
  extends WithSpinnerOverlayProps,
    NavigationProps,
    RouteComponentProps {
  profileState: {
    profile: Profile;
    reload: Function;
  };
}

interface State {
  firstVisit: boolean;
  firstVisitTraining: boolean;
  userWorkspacesResponse: WorkspaceResponseListResponse;
  showMigrationModal: boolean;
  showCreateWorkspaceModal: boolean;
}

export const Homepage = fp.flow(
  withUserProfile(),
  withNavigation,
  withRouter
)(
  class extends React.Component<Props, State> {
    private pageId = 'homepage';
    private timer: NodeJS.Timer;

    constructor(props: Props) {
      super(props);
      this.state = {
        firstVisit: undefined,
        firstVisitTraining: true,
        userWorkspacesResponse: undefined,
        showMigrationModal: false,
        showCreateWorkspaceModal: false,
      };
    }

    closeCreateWorkspaceModal = () => {
      this.setState({ showCreateWorkspaceModal: false });
    };

    componentDidMount() {
      this.props.hideSpinner();
      this.fetchWorkspaces();
      this.callProfile();
    }

    componentDidUpdate(prevProps) {
      const {
        profileState: { profile },
      } = this.props;
      if (!fp.isEqual(prevProps.profileState.profile, profile)) {
        this.callProfile();
      }
    }

    componentWillUnmount() {
      clearTimeout(this.timer);
    }

    setFirstVisit() {
      this.setState({ firstVisit: true });
      profileApi().updatePageVisits({ page: this.pageId });
    }

    async callProfile() {
      const {
        profileState: { profile, reload },
      } = this.props;

      if (fp.isEmpty(profile)) {
        setTimeout(() => {
          reload();
        }, 10000);
      } else {
        if (profile.pageVisits) {
          if (!profile.pageVisits.some((v) => v.page === this.pageId)) {
            this.setFirstVisit();
          }
          if (profile.pageVisits.some((v) => v.page === 'moodle')) {
            this.setState({ firstVisitTraining: false });
          }
        } else {
          // page visits is null; is first visit
          this.setFirstVisit();
        }
      }
    }

    async fetchWorkspaces() {
      return fetchWithSystemErrorHandler(() =>
        workspacesApi().getWorkspaces()
      ).then((response) => this.setState({ userWorkspacesResponse: response }));
    }

    userHasWorkspaces(): boolean {
      const { userWorkspacesResponse } = this.state;
      return userWorkspacesResponse?.items?.length > 0;
    }

    openMigrationModal = () => {
      this.setState({ showMigrationModal: true });
    };

    closeMigrationModal = () => {
      this.setState({ showMigrationModal: false });
    };

    render() {
      const {
        profileState: {
          profile: { migrationTestingGroup },
        },
      } = this.props;
      const { firstVisit, userWorkspacesResponse } = this.state;
      const { enableVwbMigration } = serverConfigStore.get().config;
      return (
        <React.Fragment>
          <FlexColumn style={styles.pageWrapper}>
            {serverConfigStore.get().config.enableVWBHomepageBanner ? (
              enableVwbMigration ? (
                <VwbMigrationBanner />
              ) : (
                <VwbBanner />
              )
            ) : (
              <WelcomeHeader />
            )}
            <div style={styles.fadeBox}>
              {/* The elements inside this fadeBox will be changed as part of ongoing homepage redesign work */}
              <FlexColumn style={{ justifyContent: 'flex-start' }}>
                <Workspaces
                  onChange={() => this.fetchWorkspaces()}
                  disableCreation={migrationTestingGroup}
                />
                {userWorkspacesResponse &&
                  (this.userHasWorkspaces() ? (
                    <RecentResources
                      workspaces={userWorkspacesResponse.items}
                    />
                  ) : (
                    <GettingStarted />
                  ))}
              </FlexColumn>
            </div>
          </FlexColumn>
          <QuickTourAndVideos showQuickTourInitially={firstVisit} />
          {this.state.showMigrationModal && (
            <MigrationModal onClose={this.closeMigrationModal} />
          )}
          {this.state.showCreateWorkspaceModal && (
            <VwbCreateWorkspaceModal onClose={this.closeCreateWorkspaceModal} />
          )}
        </React.Fragment>
      );
    }
  }
);

// ui/src/app/views/homepage.tsx
import {Component} from '@angular/core';
import {navigate, queryParamsStore, serverConfigStore} from 'app/utils/navigation';

import * as fp from 'lodash/fp';
import * as React from 'react';

import {
  CardButton,
  Clickable,
} from 'app/components/buttons';
import {ClrIcon} from 'app/components/icons';
import {Modal} from 'app/components/modals';
import {TooltipTrigger} from 'app/components/popups';
import {Spinner} from 'app/components/spinners';
import {profileApi} from 'app/services/swagger-fetch-clients';
import colors from 'app/styles/colors';
import {hasRegisteredAccessFetch, reactStyles, ReactWrapperBase, withUserProfile} from 'app/utils';
import {QuickTourReact} from 'app/views/quick-tour-modal';
import {RecentWork} from 'app/views/recent-work';
import {getRegistrationTasksMap, RegistrationDashboard} from 'app/views/registration-dashboard';
import {
  BillingProjectStatus,
  Profile,
} from 'generated/fetch';

export const styles = reactStyles({
  mainHeader: {
    color: colors.white, fontSize: 28, fontWeight: 400,
    display: 'flex', letterSpacing: 'normal'
  },
  backgroundImage: {
    backgroundImage: 'url("/assets/images/AoU-HP-background.jpg")',
    backgroundRepeat: 'no-repeat', backgroundSize: 'cover', height: '100%',
    marginLeft: '-1rem', marginRight: '-0.6rem', display: 'flex',
    flexDirection: 'column', justifyContent: 'space-between'
  },
  singleCard: {
    width: '87.34%', minHeight: '18rem', maxHeight: '26rem',
    display: 'flex', flexDirection: 'column', borderRadius: '5px',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    boxShadow: '0 0 2px 0 rgba(0, 0, 0, 0.12), 0 3px 2px 0 rgba(0, 0, 0, 0.12)',
    border: 'none', marginTop: '1rem'
  },
  contentWrapperLeft: {
    display: 'flex', flexDirection: 'column', paddingLeft: '3%', width: '40%'
  },
  contentWrapperRight: {
    display: 'flex', flexDirection: 'column', justifyContent: 'space-between', width: '60%'
  },
  quickRow: {
    display: 'flex', justifyContent: 'flex-start', maxHeight: '26rem',
    flexDirection: 'row', marginLeft: '4rem', padding: '1rem'
  },
  quickTourLabel: {
    fontSize: 28, lineHeight: '34px', color: colors.white, paddingRight: '2.3rem',
    marginTop: '2rem', width: '33%'
  },
  footer: {
    height: '300px', width: '100%', backgroundColor: colors.primary,
    boxShadow: '0 0 2px 0 rgba(0, 0, 0, 0.12), 0 3px 2px 0 rgba(0, 0, 0, 0.12)',
    marginTop: '2%',
  },
  footerInner: {
    display: 'flex', flexDirection: 'column', marginLeft: '5%', marginRight: '5%',
  },
  footerTitle: {
    height: '34px', opacity: 0.87, color: colors.white, fontSize: 28,
    fontWeight: 600, lineHeight: '34px', width: '87.34%', marginTop: '1.4rem'
  },
  footerText: {
    height: '176px', opacity: 0.87, color: colors.secondary, fontSize: '16px',
    fontWeight: 400, lineHeight: '30px', display: 'flex', width: '100%',
    flexDirection: 'column', flexWrap: 'nowrap', overflowY: 'auto'
  },
  linksBlock: {
    display: 'flex', marginBottom: '1.2rem', marginLeft: '1.4rem',
    flexDirection: 'column', flexShrink: 1, minWidth: 0
  },
  bottomBanner: {
    width: '100%', display: 'flex', backgroundColor: colors.primary, height: '5rem',
    paddingLeft: '3.5rem', alignItems: 'center'
  },
  logo: {
    height: '3.5rem', width: '7rem', lineHeight: '85px'
  },
  bottomLinks: {
    color: colors.white, fontSize: '0.7rem', height: '1rem',
    marginLeft: '2.5rem', fontWeight: 400
  }
});

export const Homepage = withUserProfile()(class extends React.Component<
  { profileState: { profile: Profile, reload: Function } },
  { accessTasksLoaded: boolean,
    accessTasksRemaining: boolean,
    betaAccessGranted: boolean,
    billingProjectInitialized: boolean,
    dataUseAgreementCompleted: boolean,
    eraCommonsError: string,
    eraCommonsLinked: boolean,
    firstVisit: boolean,
    firstVisitTraining: boolean,
    quickTour: boolean,
    trainingCompleted: boolean,
    twoFactorAuthCompleted: boolean,
    videoOpen: boolean,
    videoLink: string
  }> {
  private pageId = 'homepage';
  private timer: NodeJS.Timer;

  constructor(props: any) {
    super(props);
    this.state = {
      accessTasksLoaded: false,
      accessTasksRemaining: undefined,
      betaAccessGranted: undefined,
      billingProjectInitialized: false,
      dataUseAgreementCompleted: undefined,
      eraCommonsError: '',
      eraCommonsLinked: undefined,
      firstVisit: undefined,
      firstVisitTraining: true,
      quickTour: false,
      trainingCompleted: undefined,
      twoFactorAuthCompleted: undefined,
      videoOpen: false,
      videoLink: '',
    };
  }

  componentDidMount() {
    this.validateNihToken();
    this.callProfile();
    this.checkBillingProjectStatus();
  }

  componentDidUpdate(prevProps) {
    const {profileState: {profile}} = this.props;
    if (!this.state.billingProjectInitialized) {
      this.checkBillingProjectStatus();
    }
    if (!fp.isEqual(prevProps.profileState.profile, profile)) {
      this.callProfile();
    }
  }

  componentWillUnmount() {
    clearTimeout(this.timer);
  }

  async validateNihToken() {
    const token = (new URL(window.location.href)).searchParams.get('token');
    if (token) {
      try {
        await profileApi().updateNihToken({ jwt: token });
      } catch (e) {
        this.setState({eraCommonsError: 'Error saving NIH Authentication status.'});
      }
    }
  }

  setFirstVisit() {
    this.setState({firstVisit: true});
    profileApi().updatePageVisits({ page: this.pageId});
  }

  async callProfile() {
    const {profileState: {profile, reload}} = this.props;

    if (fp.isEmpty(profile)) {
      setTimeout(() => {
        reload();
      }, 10000);
    } else {

      if (!profile.betaAccessRequestTime) {
        profileApi().requestBetaAccess();
      }
      if (profile.pageVisits) {
        if (!profile.pageVisits.some(v => v.page === this.pageId)) {
          this.setFirstVisit();
        }
        if (profile.pageVisits.some(v => v.page === 'moodle')) {
          this.setState({firstVisitTraining: false});
        }
      } else {
        // page visits is null; is first visit
        this.setFirstVisit();
      }

      this.setState({
        eraCommonsLinked: getRegistrationTasksMap()['eraCommons'].isComplete(profile),
        dataUseAgreementCompleted: (serverConfigStore.getValue().enableDataUseAgreement ?
          (() => getRegistrationTasksMap()['dataUseAgreement'].isComplete(profile))() : true)
      });

      try {
        const result = await profileApi().syncComplianceTrainingStatus();
        this.setState({
          trainingCompleted: getRegistrationTasksMap()['complianceTraining'].isComplete(result)
        });
      } catch (ex) {
        this.setState({trainingCompleted: false});
        console.error('error fetching moodle training status');
      }

      try {
        const result = await profileApi().syncTwoFactorAuthStatus();
        this.setState({
          twoFactorAuthCompleted: getRegistrationTasksMap()['twoFactorAuth'].isComplete(result)
        });
      } catch (ex) {
        this.setState({twoFactorAuthCompleted: false});
        console.error('error fetching two factor auth status');
      }

      this.setState({betaAccessGranted: !!profile.betaAccessBypassTime});

      const {workbenchAccessTasks} = queryParamsStore.getValue();
      if (workbenchAccessTasks) {
        this.setState({accessTasksRemaining: true, accessTasksLoaded: true});
      } else {
        try {
          if (serverConfigStore.getValue().enforceRegistered) {
            this.setState({
              accessTasksRemaining: !hasRegisteredAccessFetch(profile.dataAccessLevel),
              accessTasksLoaded: true
            });
          } else {
            this.setState({accessTasksRemaining: false, accessTasksLoaded: true});
          }
        } catch (ex) {
          console.error('error fetching config: ' + ex.toString());
        }
      }
    }

    this.setState(
        {quickTour: this.state.firstVisit && this.state.accessTasksRemaining === false});
  }

  checkBillingProjectStatus() {
    const {profileState: {profile, reload}} = this.props;
    if (profile.freeTierBillingProjectStatus === BillingProjectStatus.Ready) {
      this.setState({billingProjectInitialized: true});
    } else {
      this.timer = setTimeout(() => {
        reload();
      }, 10000);
    }
  }

  openVideo(videoLink: string): void {
    this.setState({videoOpen: true, videoLink: videoLink});
  }


  render() {
    const {billingProjectInitialized, betaAccessGranted,
      videoOpen, accessTasksLoaded, accessTasksRemaining, eraCommonsLinked,
      eraCommonsError, firstVisitTraining, trainingCompleted, quickTour, videoLink,
      twoFactorAuthCompleted, dataUseAgreementCompleted
    } = this.state;

    const canCreateWorkspaces = billingProjectInitialized ||
      serverConfigStore.getValue().useBillingProjectBuffer;

    const quickTourResources = [
      {
        src: '/assets/images/QT-thumbnail.svg',
        onClick: () => this.setState({quickTour: true})
      }, {
        src: '/assets/images/cohorts-thumbnail.png',
        onClick: () => this.openVideo('/assets/videos/Workbench Tutorial - Cohorts.mp4')
      }, {
        src: '/assets/images/notebooks-thumbnail.png',
        onClick: () => this.openVideo('/assets/videos/Workbench Tutorial - Notebooks.mp4')
      }
    ];
    const footerLinks = [{
      title: 'Working Within Researcher Workbench',
      links: ['Researcher Workbench Mission',
        'User interface components',
        'What to do when things go wrong',
        'Contributing to the Workbench']
    },
      {
        title: 'Workspace',
        links: ['Workspace interface components',
          'User interface components',
          'Collaborating with other researchers',
          'Sharing and Publishing Workspaces']
      },
      {
        title: 'Working with Notebooks',
        links: ['Notebook interface components',
          'Notebooks and data',
          'Collaborating with other researchers',
          'Sharing and Publishing Notebooks']
      }];

    return <React.Fragment>
      <div style={styles.backgroundImage}>
        <div style={{display: 'flex', justifyContent: 'center'}}>
          <div style={styles.singleCard}>
            {accessTasksLoaded ?
              (accessTasksRemaining ?
                (<RegistrationDashboard eraCommonsLinked={eraCommonsLinked}
                                        eraCommonsError={eraCommonsError}
                                        trainingCompleted={trainingCompleted}
                                        firstVisitTraining={firstVisitTraining}
                                        betaAccessGranted={betaAccessGranted}
                                        twoFactorAuthCompleted={twoFactorAuthCompleted}
                                        dataUseAgreementCompleted={dataUseAgreementCompleted}/>
                ) : (
                  <div style={{display: 'flex', flexDirection: 'row', paddingTop: '2rem'}}>
                    <div style={styles.contentWrapperLeft}>
                      <div style={styles.mainHeader}>Researcher Workbench</div>
                      <TooltipTrigger content={<div>Your Firecloud billing project is still being
                        initialized. Workspace creation will be available in a few minutes.</div>}
                                      disabled={canCreateWorkspaces}>
                        <CardButton disabled={!canCreateWorkspaces}
                                    onClick={() => navigate(['workspaces/build'])}
                                    style={{margin: '1.9rem 106px 0 3%'}}>
                          Create a <br/> New Workspace
                          <ClrIcon shape='plus-circle' style={{height: '32px', width: '32px'}}/>
                        </CardButton>
                      </TooltipTrigger>
                    </div>
                    <div style={styles.contentWrapperRight}>
                      <a onClick={() => navigate(['workspaces'])}
                         style={{fontSize: '14px', color: colors.white}}>
                        See All Workspaces</a>
                      <div style={{marginRight: '3%', display: 'flex', flexDirection: 'column'}}>
                        <div style={{color: colors.white, height: '1.9rem'}}>
                          <div style={{marginTop: '.5rem'}}>Your Last Accessed Items</div>
                        </div>
                        <RecentWork dark={true}/>
                      </div>
                    </div>
                  </div>)
                ) :
              <Spinner dark={true} style={{width: '100%', marginTop: '5rem'}}/>}
          </div>
        </div>
        <div>
          <div style={styles.quickRow}>
            <div style={styles.quickTourLabel}>Quick Tour & Videos</div>
            {quickTourResources.map((thumbnail, i) => {
              return <React.Fragment key={i}>
                <Clickable onClick={thumbnail.onClick}
                           data-test-id={'quick-tour-resource-' + i}>
                  <img style={{maxHeight: '121px', width: '8rem', marginRight: '1rem'}}
                       src={thumbnail.src}/>
                </Clickable>
              </React.Fragment>;
            })}
          </div>
          <div>
            <div style={styles.footer}>
              <div style={styles.footerInner}>
                <div style={styles.footerTitle}>
                  How to Use the All of Us Researcher Workbench</div>
                <div style={{display: 'flex', justifyContent: 'flex-end'}}>
                  <TooltipTrigger content='Coming Soon' side='left'>
                    <a href='#' style={{color: colors.white}}>See all documentation</a>
                  </TooltipTrigger>
                </div>
                <div style={{display: 'flex', flexDirection: 'row',
                  width: '87.34%', justifyContent: 'space-between'}}>
                  {footerLinks.map((col, i) => {
                    return <React.Fragment key={i}>
                      <div style={styles.linksBlock}>
                        <div style={styles.footerText}>
                          <div style={{color: colors.white, marginTop: '2%'}}>{col.title}</div>
                          <ul style={{color: colors.secondary}}>
                            {col.links.map((link, ii) => {
                              return <li key={ii}>
                                <a href='#' style={{color: colors.secondary}}>{link}</a>
                              </li>;
                            } )}
                          </ul>
                        </div>
                      </div>
                    </React.Fragment>;
                  })}
                </div>
              </div>
            </div>
            <div style={styles.bottomBanner}>
              <div style={styles.logo}>
                <img src='/assets/images/all-of-us-logo-footer.svg'/>
              </div>
              <div style={styles.bottomLinks}>Privacy Policy</div>
              <div style={styles.bottomLinks}>Terms of Service</div>
            </div>
          </div>
        </div>

      </div>

      {quickTour &&
        <QuickTourReact closeFunction={() => this.setState({quickTour: false})} />}
      {videoOpen && <Modal width={900}>
        <div style={{display: 'flex'}}>
          <div style={{flexGrow: 1}}></div>
          <Clickable onClick={() => this.setState({videoOpen: false})}>
            <ClrIcon
              shape='times'
              size='24'
              style={{color: colors.accent, marginBottom: 17}}
            />
          </Clickable>
        </div>
        <video width='100%' controls autoPlay>
          <source src={videoLink} type='video/mp4'/>
        </video>
      </Modal>}
    </React.Fragment>;
  }

});

@Component({
  template: '<div #root style="height: 100%"></div>'
})
export class HomepageComponent extends ReactWrapperBase {
  constructor() {
    super(Homepage, []);
  }
}
